// The route is playful fiction; the field notes describe the real ecosystem.
export const ZONES = [
  { at: 0, key: 'zurich', name: 'DFINITY HQ', tag: 'One IT guy. One very ambitious bug.', color: '#a9ffdd', sky: '#c4d9e3', speaker: 'DFINITY IT · ZÜRICH', message: 'The bug escaped localhost. Launch from the roof. We are calling this a controlled experiment.', glyph: '∞', fact: 'Your departure point is a playful interpretation of the DFINITY office in Zürich.', url: 'https://dfinity.org/' },
  { at: 200, key: 'caffeine', name: 'Caffeine ignition', tag: 'Prompt: send this bug to space.', color: '#ffc581', sky: '#8b8dbd', speaker: 'CAFFEINE · IGNITION', message: 'You asked for a small improvement. I built an interdimensional launch sequence. You are welcome.', glyph: '☕', fact: 'Caffeine builds full-stack apps from natural-language conversations and runs them on the Internet Computer.', url: 'https://help.caffeine.ai/hc/en-us/articles/46899814439700-How-Caffeine-Works' },
  { at: 500, key: 'motoko', name: 'Motoko compiler', tag: 'persistent actor { bug = true }', color: '#cba5ff', sky: '#191d42', speaker: 'MOTOKO · COMPILER ONLINE', message: 'Motoko has found you. Watch its pink cannon charge, then dodge the incoming pulse. Two hits debug the ghost.', glyph: '{ }', fact: 'Motoko compiles to WebAssembly. Its actor model and orthogonal persistence suit stateful canister applications.', url: 'https://docs.internetcomputer.org/languages/motoko/' },
  { at: 900, key: 'canisters', name: 'Canister orbit', tag: 'Code and state. Same spacecraft.', color: '#63eeff', sky: '#070d26', speaker: 'CANISTER · STATE PRESERVED', message: 'Welcome aboard. Your code and memory travel together. Collect a capsule for one emergency bounce.', glyph: '▥', fact: 'A canister combines WebAssembly code with its own persistent state and communicates through messages.', url: 'https://docs.internetcomputer.org/concepts/canisters/' },
  { at: 1350, key: 'identity', name: 'Identity gateway', tag: 'Passkey accepted. Bug suspicious.', color: '#94ffcc', sky: '#08272e', speaker: 'INTERNET IDENTITY · ACCESS', message: 'Human verified. Bug tolerated. Pick up a key: its arcade shield absorbs your next hazard collision.', glyph: '⌘', fact: 'Internet Identity supports passkey-based authentication for applications on the Internet Computer.', url: 'https://docs.internetcomputer.org/guides/authentication/internet-identity/' },
  { at: 1850, key: 'oisy', name: 'OISY nebula', tag: 'A wallet for a very strange journey.', color: '#b7afff', sky: '#191334', speaker: 'OISY · ASSET DETECTED', message: 'Asset identified: one airborne bug. Collect an OISY orb to pull nearby cycle rings into your flight.', glyph: '◉', fact: 'OISY is a web wallet supporting multiple networks, including Bitcoin, Ethereum and the Internet Computer.', url: 'https://docs.oisy.com/introduction/why-oisy-wallet' },
  { at: 2400, key: 'fusion', name: 'Chain Fusion', tag: 'Different chains. One flight path.', color: '#ffbe7b', sky: '#271432', speaker: 'CHAIN FUSION · CROSSING', message: 'Bitcoin. Ethereum. Internet Computer. Three worlds connected. Catch a fusion gate for a serious speed boost.', glyph: '⟐', fact: 'Chain Fusion enables canisters to interact with other blockchains through native integrations and threshold signing.', url: 'https://learn.internetcomputer.org/hc/en-us/articles/34329023770260-Chain-Fusion' },
  { at: 3000, key: 'engines', name: 'Cloud Engines', tag: 'Your cloud has left the building.', color: '#69e4ff', sky: '#091f34', speaker: 'OPEN CLOUD · ENGINE ROOM', message: 'Dedicated compute, somewhere above Zürich. Your next infrastructure request has wings. Keep the engines lit.', glyph: '⬡', fact: 'Cloud Engines provide dedicated subnet capacity. Open Cloud offers a place to discover and use this infrastructure.', url: 'https://opencloud.org/' },
  { at: 3700, key: 'nns', name: 'NNS constellation', tag: 'Proposal: let the bug ship.', color: '#ff92c5', sky: '#291129', speaker: 'NNS · GOVERNANCE CHANNEL', message: 'Proposal submitted: classify this bug as a feature. Navigate the constellation. Democracy cannot steer for you.', glyph: '✳', fact: 'The Network Nervous System is the on-chain governance system that manages the Internet Computer network.', url: 'https://docs.internetcomputer.org/concepts/governance/' },
  { at: 4400, key: 'mainnet', name: 'Internet Computer', tag: 'From a Zürich rooftop to infinity.', color: '#91ffe0', sky: '#10122f', speaker: 'DFINITY IT · SIGNAL RECEIVED', message: 'You made it. The internet is your computer now. The original ticket is still marked “in progress”.', glyph: '∞', fact: 'The Internet Computer is a network for running applications and services in canister smart contracts.', url: 'https://docs.internetcomputer.org/concepts/canisters/' },
];
export const POWERUPS = {
  coffee: { name: 'Caffeine', effect: 'Forward + upward boost', color: '#ffc581' },
  compiler: { name: 'Motoko', effect: 'Compiler slingshot', color: '#cba5ff' },
  canister: { name: 'Canister', effect: 'One emergency bounce', color: '#63eeff' },
  identity: { name: 'Internet Identity', effect: 'Blocks one hazard', color: '#94ffcc' },
  oisy: { name: 'OISY', effect: '8 seconds of cycle magnet', color: '#b7afff' },
  fusion: { name: 'Chain Fusion', effect: 'Cross-chain speed burst', color: '#ffbe7b' },
  portal: { name: 'Cloud Engine', effect: 'Lift + 50 K cycles', color: '#69e4ff' },
  neuron: { name: 'NNS neuron', effect: '50 K cycles + lift', color: '#ff92c5' },
};
