export const content = {
  de: {
    title: "Kebabstack | IT-Suite für KMU und Startups auf OpenCloud",
    description:
      "Die offene IT-Suite für Startups und KMU. Menschen, Geräte, Support und Verträge verbinden — auf deiner Cloud Engine, mit Code zum Weiterentwickeln.",
    nav: ["Der Stack", "Die Technologie", "Selbst weiterbauen", "Pilot planen"],
    skip: "Zum Inhalt",
    menu: "Menü",
    close: "Menü schließen",
    eyebrow: "DIE IT-SUITE, DIE ZUSAMMENHÄNGE NUTZT.",
    hero: ["Deine IT.", "Weniger Routine.", "Mehr Freiraum."],
    intro:
      "Kebabstack verbindet Menschen, Geräte, Support und Verträge auf deiner Cloud Engine. Damit deine IT weniger nachhalten muss und mehr weiterbringen kann.",
    heroPrimary: "Stack entdecken",
    heroSecondary: "Wie funktioniert das?",
    heroNotes: [
      "MIT-lizenziert",
      "Auf deiner Cloud Engine",
      "Aktuell in Alpha",
    ],
    illustration: "Produktillustration · Beispieldaten",
    ribbon: [
      "Ein gemeinsames Verzeichnis",
      "Verbundene Anwendungen",
      "Dein eigener Quellcode",
    ],
    suiteKicker: "01 / DER STACK",
    suiteTitle: "Gute Werkzeuge.\nBessere Zusammenarbeit.",
    suiteIntro:
      "Entdecke konkrete Abläufe aus der implementierten Alpha. Die Beispiele sind nachgestellt: Namen, Geräte und Zahlen sind Beispieldaten, keine Kundenergebnisse.",
    alpha: "IMPLEMENTIERT · ALPHA",
    explorerLabel: "Anwendungen entdecken",
    modules: [
      {
        id: "hub",
        name: "Hub",
        category: "Menschen & Rechte",
        icon: "people",
        title: "Ein Einstieg für dein Team.",
        text: "Personen, Gruppen und App-Rechte zentral verwalten. Gemeinsam anmelden, zwischen Apps wechseln und in Operations sehen, wo Arbeit ansteht.",
        features: [
          "Passkeys & SSO; Verzeichnis aus Okta, SCIM oder OpenTeam",
          "Zentrale Rollen und App-Berechtigungen",
          "Operations-Übersicht und gekoppelte Team-Displays",
        ],
        note: "Personen und Rechte bilden die gemeinsame Grundlage.",
      },
      {
        id: "desk",
        name: "Desk",
        category: "Support & Rufbereitschaft",
        icon: "ticket",
        title: "Ein Austritt beginnt nicht immer mit einem Ticket.",
        text: "Wird eine bekannte Person in Okta, OpenTeam, per SCIM oder direkt im Hub deaktiviert, fängt Desk die Folgearbeit auf. IT prüft den Anlass und hat den erlaubten Kontext aus den verbundenen Apps direkt im Fall.",
        features: [
          "Automatischer Prüffall statt vergessener Nacharbeit",
          "Hardware-Fortschritt aus Assets statt doppelter Checklisten",
          "Auch Kundenprojekte, Rufbereitschaft und HR/Finance-Berichte",
        ],
        note: "Nach Eingang im Hub; Synchronisation und App-Verfügbarkeit können verzögern. Bestätigte mobile Alarmierung ist weiterhin geplant.",
      },
      {
        id: "assets",
        name: "Assets",
        category: "Geräte & Inventar",
        icon: "laptop",
        title: "Wissen, was da ist. Und bei wem.",
        text: "Hardware erfassen, Menschen zuordnen und Übergaben nachvollziehen. Vorhandene MDM- und Apple-Daten importieren und Rückgaben oder Verkäufe begleiten.",
        features: [
          "Inventar und Zuordnungshistorie",
          "Ausgabe, Rückgabe und Wiederverwendung",
          "Hardware-Verkäufe mit eigenem Dealroom",
        ],
        note: "Inventarisierung ergänzt deine Geräteverwaltung.",
      },
      {
        id: "trust",
        name: "Trust",
        category: "Gerätezustand",
        icon: "shield",
        title: "Gerätezustand mit Belegen.",
        text: "Ein lesender osquery-Agent liefert Systeminformationen. Trust zeigt aktuelle Prüfungen, fehlende Nachweise und Geräte, um die sich die IT kümmern sollte.",
        features: [
          "Prüfungen und nachvollziehbare Ergebnisse",
          "Ansicht der eigenen Geräte für Mitarbeitende",
          "Behebung über eure bestehenden Management-Werkzeuge",
        ],
        note: "Transparente Zustandsprüfung. Kein Ersatz für MDM.",
      },
      {
        id: "contracts",
        name: "Contracts",
        category: "Software & Verträge",
        icon: "document",
        title: "Die nächste Verlängerung im Blick.",
        text: "Verträge hochladen, optionale KI-Vorschläge prüfen und Kosten, Zuständigkeiten sowie Entscheidungsfristen festhalten. Damit Entscheidungen rechtzeitig vorbereitet sind.",
        features: [
          "SaaS-Übersicht und Lizenzzuordnungen",
          "Verlängerungen und Kündigungsfristen",
          "Berichte mit getrennten Währungssummen",
        ],
        note: "Zuordnung dokumentiert Lizenzen; sie bucht keine Anbieter-Seats.",
      },
      {
        id: "forms",
        name: "Forms",
        category: "Formulare & Review",
        icon: "form",
        title: "Vom Formular zur Entscheidung.",
        text: "Formulare erstellen, Antworten über öffentliche Links sammeln und gemeinsam prüfen. Mit Zuständigkeiten, Bewertungen und einer klaren Entscheidung am Ende.",
        features: [
          "Formular-Builder und öffentliche Links",
          "Review-Pipeline mit Notizen und Bewertungen",
          "Freigaben, Auswertungen und CSV-Export",
        ],
        note: "Öffentliche Teilnahme; interne Prüfung mit Zugriffsrechten.",
      },
      {
        id: "watch",
        name: "Watch",
        category: "Domains & DNS",
        icon: "globe",
        title: "Domains brauchen Aufmerksamkeit.",
        text: "DNS-Konfiguration, Domain-Befunde und bekannte Ablaufdaten überwachen. Ergebnisse mit Belegen prüfen und bei Bedarf Benachrichtigungen einschalten.",
        features: [
          "Domain- und DNS-Monitoring",
          "Befunde mit Zeitstempel und Nachweis",
          "Bekannte Ablaufdaten im Blick",
        ],
        note: "DNS- und Domain-Nachweise, kein HTTP-Uptime-Monitor.",
      },
      {
        id: "crumbs",
        name: "Crumbs",
        category: "Website-Analytics",
        icon: "chart",
        title: "Traffic sehen. Den nächsten Schritt verstehen.",
        text: "Welche Quellen bringen Interesse – und welche führen zur Anfrage? Crumbs verbindet Traffic, AI-Empfehlungen, Ziele und Umsatz. Gespeicherte Filter und Funnels machen wiederkehrende Auswertungen einfach; mehrere Websites bleiben gemeinsam im Blick.",
        features: [
          "AI-Quellen, Kampagnenkanäle und Scroll-Ziele",
          "Funnels und Umsatz nach Quelle, getrennt je Währung",
          "Website-Übersicht, Hub-Rechte und Datenexport",
          "Google Search Console und Data Studio mit Einrichtungsanleitung",
        ],
        note: "Nativer Collector, ohne Cookies oder Browser-Speicher. Google-Anbindungen sind optional und benötigen eigene Konfiguration. Keine dauerhaften Besucherprofile; Datenschutz und Kapazität bleiben Teil der Einführung.",
      },
      {
        id: "phone",
        name: "Phone",
        category: "iOS & Android",
        icon: "phone",
        planned: true,
        tabStatus: "Geplant",
        status: "GEPLANT · NOCH NICHT VERFÜGBAR",
        illustration: "Konzeptillustration · geplant",
        title: "Dein Stack. Auch unterwegs.",
        text: "Geplant ist eine Begleit-App für iOS und Android: den eigenen Stack verbinden, bestehende Web-Apps öffnen und Incidents direkt auf dem Telefon empfangen und übernehmen.",
        features: [
          "Widerrufbare Gerätefreigabe für bequeme Anmeldung",
          "Native Incident-Alarme mit direkter Übernahme",
          "Alarmbereitschafts-Check nach Anmeldung und Rückkehr, mit Testalarm",
        ],
        note: "Noch nicht verfügbar. Push benötigt zusätzliche Infrastruktur und Plattformfreigaben. Einstellungsänderungen sind nicht jederzeit sofort erkennbar; keine Zustellgarantie.",
      },
    ],
    moreTitle: "Und die Basis für den Betrieb.",
    supporting: [
      [
        "Kitchen",
        "Installation & Updates",
        "Installiert Module und spielt geprüfte Releases ein. Nach der Einrichtung bedienst du die Apps-Verwaltung im Hub.",
        "layers",
      ],
      [
        "Vault",
        "Snapshots & Wiederherstellung",
        "Sicherungspunkte erstellen, planen und wiederherstellen. Je Canister — kein atomarer Backup-Stand der ganzen Suite.",
        "archive",
      ],
      [
        "kebab-mcp",
        "Dein KI-Assistent",
        "Verbindet deinen Assistenten mit den Apps. Er handelt mit deinen bestehenden Rechten; Integrationen und Datenflüsse konfigurierst du.",
        "spark",
      ],
      [
        "Ship the Bug",
        "Eine kleine Pause",
        "Ein Spiel in 2D und 3D. Öffentlich spielbar, mit optionalem Hub-Profil und freiwilligen Bestenlisten.",
        "bug",
      ],
    ],
    engineKicker: "02 / DIE TECHNOLOGIE, VERSTÄNDLICH",
    engineTitle: "Eine andere Grundlage.\nEin vertrauter IT-Alltag.",
    engineIntro:
      "Dein Team arbeitet im Browser. Darunter läuft kebabstack auf einer Cloud Engine: einer konfigurierbaren Ausführungsumgebung auf dem Internet Computer.",
    layerLabels: ["DEIN TEAM", "DEINE ANWENDUNGEN", "DEINE INFRASTRUKTUR"],
    layers: [
      ["Browser", "Anmelden. Arbeiten. Weiterkommen."],
      ["kebabstack", "Gemeinsamer Hub. Verbundene Werkzeuge."],
      ["Cloud Engine", "Ausgewählte Nodes betreiben Code und Daten."],
    ],
    enginePoints: [
      [
        "Cloud Engine",
        "Die Umgebung für deine Apps.",
        "Sie führt Anwendungen über mehrere Rechner, sogenannte Nodes, aus. Betreiber und Standorte hängen von deiner Engine-Konfiguration ab.",
      ],
      [
        "Internet Computer (IC / ICP)",
        "Das Protokoll darunter.",
        "Es koordiniert die Ausführung und Replikation. Dein Team bedient Web-Apps; für den Betrieb lernt eure IT die Plattform und ihre Werkzeuge kennen.",
      ],
      [
        "Canister & Motoko",
        "Anwendungslogik mit dauerhaftem Zustand.",
        "Ein Canister enthält Backend-Code und gespeicherte Anwendungsdaten. Die Motoko-Backends benötigen keinen separaten SQL-Dienst. Auch Crumbs kann nativ erfassen; externe Integrationen bleiben bewusst konfigurierte Dienste.",
      ],
    ],
    opencloudText:
      "OpenCloud ist ein Zugang zur Bereitstellung und Verwaltung von Cloud Engines. kebabstack ist die IT-Suite, die darauf läuft.",
    opencloudLink: "OpenCloud kennenlernen",
    engineNote:
      "Mehr Kontrolle entsteht durch bewusste Konfiguration. Datenstandort, Vertraulichkeit gegenüber Infrastrukturbetreibern und externe Datenflüsse müssen für eure Umgebung geprüft werden. Die Abhängigkeit von ICP bleibt.",
    buildKicker: "03 / DEIN STACK KANN MEHR WERDEN",
    buildTitle: "Eure Abläufe sind eigen.\nEure Software darf es auch sein.",
    buildIntro:
      "Ein zusätzliches Feld. Ein anderer Freigabeprozess. Eine ganz neue App. Mit offenem Quellcode und einem gemeinsamen SDK baut ihr auf dem auf, was schon da ist.",
    buildSteps: [
      [
        "01",
        "Anpassen",
        "Bestehende Apps forken und Oberflächen oder Geschäftslogik an eure Arbeitsweise anpassen.",
      ],
      [
        "02",
        "Erweitern",
        "Eine eigene App mit dem SDK anbinden: Anmeldung, Personenverzeichnis und gemeinsame Navigation wiederverwenden.",
      ],
      [
        "03",
        "Weiterentwickeln",
        "Selbst programmieren oder mit einem Coding-Agent arbeiten. Änderungen prüfen, mit Daten testen und kontrolliert ausrollen.",
      ],
    ],
    codeLabel: "DEIN AUSGANGSPUNKT",
    codeComment: "Deine Idee wird Teil des Stacks.",
    tree: [
      "Gemeinsame Anmeldung & Rechte",
      "Deine Service-Prozesse",
      "Deine Geräte & Zuordnungen",
      "Startpunkt für eine eigene App",
      "Anleitung für Team & Coding-Agent",
    ],
    licenseTitle: "MIT. Auch für euren eigenen Weg.",
    licenseText:
      "Die Lizenz erlaubt Nutzung, Änderung und Weitergabe, auch kommerziell. Der Lizenz- und Copyright-Hinweis bleibt erhalten.",
    licenseLink: "Lizenz lesen",
    buildNote:
      "Motoko hilft, strukturell inkompatible Zustandsänderungen zu erkennen. Fachliche Tests, Berechtigungsprüfungen, Upgrade-Tests und Wiederherstellung bleiben Teil eurer Arbeit.",
    economicsKicker: "04 / DIE ENTSCHEIDUNG",
    economicsTitle: "Keine Gebühr pro Kopf.\nEine ehrliche Gesamtrechnung.",
    economicsIntro:
      "kebabstack erhebt keine Lizenzgebühr pro Person. Was es euch insgesamt kostet, entscheidet sich an Infrastruktur, Integrationen und dem Aufwand eures Teams.",
    economicsCards: [
      [
        "01",
        "Gemeinsame Grundlagen",
        "Ein Verzeichnis und eine Anmeldung können doppelte Integrationsarbeit reduzieren.",
      ],
      [
        "02",
        "Weniger separate Dienste",
        "Die Motoko-Backends speichern Daten direkt im Canister. Auch Crumbs kann ohne separaten Collector laufen. Zusätzliche Integrationen und deren Betrieb gehören in eure Kalkulation.",
      ],
      [
        "03",
        "Eigene Prioritäten",
        "Quellcode und App-Kontrolle erlauben eigene Erweiterungen. Pflege, Support und Updates gehören dann ebenfalls zu euch.",
      ],
    ],
    costHeading: "SO VERGLEICHT IHR FAIR",
    costParts: [
      "kebabstack-Lizenz",
      "Infrastruktur",
      "Externe APIs",
      "Betriebszeit",
      "Anteilig Migration",
    ],
    costNote:
      "Betriebszeit × interner Stundensatz; Migration über einen festgelegten Zeitraum verteilen. Nur tatsächlich kündbare Abos als Einsparung rechnen. Noch kein validierter Kosten- oder Kapazitätsbenchmark.",
    startKicker: "05 / DER NÄCHSTE SCHRITT",
    startTitle: "Klein anfangen.\nMit echten Fragen.",
    startIntro:
      "Plant einen abgegrenzten Pilot mit Testdaten. Nicht die Anzahl installierter Apps entscheidet, sondern ob eure Abläufe damit besser funktionieren.",
    pilot: [
      [
        "Umgebung festlegen",
        "Engine, verantwortliche IT, Controller und Wiederherstellung klären. Der erste Aufbau erfolgt über die Kommandozeile.",
      ],
      [
        "Einen Ablauf ausprobieren",
        "Fünf Testpersonen anlegen, ein Gerät zuweisen, eine Anfrage genehmigen und eine Person wieder sperren.",
      ],
      [
        "Betrieb erproben",
        "Update, Hub-Ausfall und Wiederherstellung mit Testdaten durchspielen. Zeit, Fehler und verbleibende Fremdsysteme festhalten.",
      ],
    ],
    downloadPilot: "Pilot-Checkliste herunterladen",
    roadmapTitle: "Wo wir heute stehen.",
    roadmap: [
      [
        "Alpha",
        "Die Suite einschließlich Crumbs und Desk-Rufbereitschaft ist als Alpha implementiert. Für abgegrenzte Tests und technische Evaluation.",
      ],
      [
        "Geplant",
        "Phone für iOS und Android: mobiler Stack-Zugang, Incident-Alarme und Alarmbereitschafts-Check. Noch nicht verfügbar.",
      ],
      [
        "Öffentlich verfügbar",
        "Die komplette Alpha als MIT-Quellcode: Apps, SDK, Tests, Installationshilfen und Designstandard auf GitHub.",
      ],
      [
        "Coming soon",
        "Integration in den OpenCloud Marketplace. Noch kein Marketplace-Installationsweg verfügbar.",
      ],
    ],
    roadmapNote:
      "Quellcode prüfen, lokal testen und einen abgegrenzten Pilot starten. Die manuelle Installation ist im öffentlichen Repository dokumentiert.",
    faqTitle: "Gute Fragen. Klare Antworten.",
    faq: [
      [
        "Passt Kebabstack zu OpenSaaS und OpenTeam?",
        "Hub kann OpenTeam als optionale Verzeichnisquelle nutzen: Personen und Beschäftigungsstatus werden nach einer geprüften Vorschau übernommen und alle fünf Minuten abgeglichen. App-Rechte und Finance bleiben zentral in Hub. Der Connector ist als Alpha gegen die Verzeichnisschnittstelle lokal getestet; prüft eure konkrete OpenTeam-Version im Pilot. Gemeinsames OpenSaaS-Login und weitere Suite-Anbindungen sind damit noch nicht enthalten.",
        "https://github.com/kebabstack/kebabstack-source/blob/main/docs/OPENTEAM.md",
        "Einrichtung und Kompatibilitätsumfang",
      ],
      [
        "Muss mein Team Blockchain oder Krypto verstehen?",
        "Für die tägliche Arbeit bedient es ganz normale Web-Oberflächen. Die IT benötigt Plattformkenntnisse für Einrichtung und Betrieb. Cloud Engines werden als Infrastruktur betrieben; für Mitarbeitende ist kein eigener Token-Kauf Teil des App-Workflows.",
      ],
      [
        "Ersetzt kebabstack unsere komplette IT-Landschaft?",
        "Das hängt von euren Anforderungen ab. Die Suite deckt konkrete Aufgaben ab, ist aber kein vollständiger Ersatz für jedes IAM-, ITSM- oder Endpoint-Management-Produkt. E-Mail, Geräteverwaltung und weitere externe Dienste können weiterhin nötig sein.",
      ],
      [
        "Können wir den Code wirklich selbst ändern?",
        "Ja. Die vorhandene MIT-Lizenz erlaubt eigene Anpassungen, kommerzielle Nutzung und Weitergabe mit Lizenzhinweis. Die gesamte Alpha steht öffentlich auf GitHub. Enthaltene Drittbibliotheken und Bilder behalten ihre jeweiligen Lizenzen. Die Backends verwenden Motoko, die Frontends Web-Technologien; das SDK enthält eine Beispiel-App.",
      ],
      [
        "Sind unsere Daten automatisch privat oder in der Schweiz?",
        "Nein. Standort und Betreiber hängen von der gewählten Infrastruktur ab. Replikation ist keine Ende-zu-Ende-Verschlüsselung gegenüber Node-Betreibern. Identitätsanbieter, Slack oder KI-Dienste können zusätzliche Datenflüsse erzeugen. Prüft sie für euren konkreten Einsatz.",
      ],
      [
        "Wie funktionieren Updates, Backups und Zugriffsentzug?",
        "Kitchen verwaltet Releases; Vault bietet Snapshots je Canister. Es gibt keinen atomaren Suite-Backup und damit allein kein externes Disaster Recovery. Gebündelte Apps sperren ohne frische Hub-Bestätigung nach spätestens 60 Sekunden Verzeichnisalter; Verzögerungen externer Identitätsquellen kommen hinzu. Ein Hub-Ausfall unterbricht damit den App-Zugriff.",
      ],
      [
        "Ist das schon produktionsreif?",
        "Der aktuelle Stand ist Alpha. Funktionen sind implementiert, aber Kosten, Kapazität und Verfügbarkeit sind nicht durch belastbare Benchmarks abgesichert. Startet mit einem abgegrenzten Pilot und entscheidet anhand eurer Anforderungen, Tests und verfügbaren Betriebskapazität.",
      ],
    ],
    endTitle: "Fertige Bausteine.\nOffene Möglichkeiten.",
    endLink: "Zurück zum Stack",
    footerTag: "Die IT-Suite zum Selbstweiterdenken.",
    footerStatus: "Alpha · OpenCloud Marketplace coming soon",
    footerLicense: "MIT-Lizenz",
    footerVersion: "Version",
    analyticsPrivacyTitle: "Datenschutz & Crumbs",
    analyticsPrivacy: "Wir nutzen unser eigenes Crumbs für Seitenaufrufe, Verweisquellen, Verweildauer, Scrolltiefe, Linkklicks, App-Auswahl und Downloads. Die Analyse setzt keine Cookies und speichert nichts im Browser. Do Not Track und Global Privacy Control verhindern die Erfassung. Deine Farbschema-Auswahl wird unabhängig davon nur lokal gespeichert.",
    analyticsProcessing: "Der Gateway und die Cloud Engine verarbeiten dabei IP-Adresse und Browserinformationen. Crumbs bildet täglich wechselnde, websitebezogene Besucherkennungen; rohe IP-Adressen und vollständige Browserkennungen werden nicht in den Analyseereignissen gespeichert. Ereignisse werden nach {days} Tagen aus Berichten entfernt und anschließend schrittweise gelöscht. Infrastrukturprotokolle und Sicherungen haben eigene Aufbewahrungsregeln. Die dargestellten Produkt-Demos bleiben Beispieldaten.",
    footerPrivacy:
      "Diese Seite verwendet keine Analyse- oder Marketing-Tracker. Deine Farbschema-Auswahl wird nur lokal gespeichert. Die Infrastruktur kann technische Zugriffsprotokolle verarbeiten.",
    notFound: "Diese Seite gibt es hier nicht.",
    backHome: "Zur Startseite",
    theme: "Farbschema",
    themeOptions: ["System", "Hell", "Dunkel"],
  },
  en: {
    title: "Kebabstack | Connected IT tools for startups on OpenCloud",
    description:
      "The open IT suite for startups and SMEs. Connect people, devices, support and contracts — on your Cloud Engine, with code your team can make its own.",
    nav: ["The stack", "The technology", "Make it yours", "Plan a pilot"],
    skip: "Skip to content",
    menu: "Menu",
    close: "Close menu",
    eyebrow: "AN IT SUITE THAT CONNECTS THE DOTS.",
    hero: ["Your IT.", "Less busywork.", "More possibility."],
    intro:
      "Kebabstack connects people, devices, support and contracts on your Cloud Engine. Less chasing the next task. More room to make things better.",
    heroPrimary: "Explore the stack",
    heroSecondary: "How does it work?",
    heroNotes: ["MIT licensed", "On your Cloud Engine", "Currently in alpha"],
    illustration: "Product illustration · Sample data",
    ribbon: [
      "One shared directory",
      "Connected applications",
      "Code you can make your own",
    ],
    suiteKicker: "01 / THE STACK",
    suiteTitle: "Useful tools.\nBetter together.",
    suiteIntro:
      "Explore real workflows from the implemented alpha. These are illustrated examples: names, devices and numbers are sample data, not customer results.",
    alpha: "IMPLEMENTED · ALPHA",
    explorerLabel: "Explore applications",
    modules: [
      {
        id: "hub",
        name: "Hub",
        category: "People & access",
        icon: "people",
        title: "One starting point for your team.",
        text: "Manage people, groups and app access centrally. Share sign-in, move between apps and use Operations to see what needs attention.",
        features: [
          "Passkeys & SSO; directory from Okta, SCIM or OpenTeam",
          "Central roles and app permissions",
          "Operations overview and paired team displays",
        ],
        note: "People and permissions form the shared foundation.",
      },
      {
        id: "desk",
        name: "Desk",
        category: "Support & on-call",
        icon: "ticket",
        title: "A departure does not always start with a ticket.",
        text: "When a known person is deactivated in Okta, OpenTeam, through SCIM or directly in Hub, Desk picks up the follow-up. IT reviews the reason, with authorized context from connected apps alongside the case.",
        features: [
          "Automatic review instead of forgotten follow-up",
          "Hardware progress from Assets instead of duplicate checklists",
          "Also customer projects, on-call and HR/Finance reporting",
        ],
        note: "After the change reaches Hub; synchronization and app availability can cause delays. Verified mobile alerting remains planned.",
      },
      {
        id: "assets",
        name: "Assets",
        category: "Devices & inventory",
        icon: "laptop",
        title: "Know what you have. And who has it.",
        text: "Record hardware, assign it to people and follow its handover history. Import existing MDM and Apple data, manage returns and coordinate sales.",
        features: [
          "Inventory and assignment history",
          "Issue, return and reuse",
          "Hardware sales with a dedicated dealroom",
        ],
        note: "Inventory complements your device management.",
      },
      {
        id: "trust",
        name: "Trust",
        category: "Device posture",
        icon: "shield",
        title: "Device posture, with evidence.",
        text: "A read-only osquery agent reports system facts. Trust shows current checks, missing evidence and the devices that need IT attention.",
        features: [
          "Checks with inspectable results",
          "Employees can see their own devices",
          "Remediation through your existing management tools",
        ],
        note: "Transparent posture checks. Not an MDM replacement.",
      },
      {
        id: "contracts",
        name: "Contracts",
        category: "Software & contracts",
        icon: "document",
        title: "Stay ahead of the next renewal.",
        text: "Upload contracts, review optional AI suggestions and record costs, owners and decision dates. Give the team time to make a considered decision.",
        features: [
          "SaaS overview and licence allocations",
          "Renewals and cancellation deadlines",
          "Reports with separate currency totals",
        ],
        note: "Allocations record licences; they do not provision vendor seats.",
      },
      {
        id: "forms",
        name: "Forms",
        category: "Forms & review",
        icon: "form",
        title: "From submission to decision.",
        text: "Build forms, collect responses through public links and review them together. With owners, ratings and a clear decision at the end.",
        features: [
          "Form builder and public links",
          "Review pipeline with notes and ratings",
          "Sharing, insights and CSV export",
        ],
        note: "Public participation; internal review with access controls.",
      },
      {
        id: "watch",
        name: "Watch",
        category: "Domains & DNS",
        icon: "globe",
        title: "Give your domains some attention.",
        text: "Monitor DNS configuration, domain findings and known expiry dates. Review the evidence and enable notifications where needed.",
        features: [
          "Domain and DNS monitoring",
          "Findings with timestamps and evidence",
          "Known expiry dates in view",
        ],
        note: "DNS and domain evidence, not HTTP uptime monitoring.",
      },
      {
        id: "crumbs",
        name: "Crumbs",
        category: "Website analytics",
        icon: "chart",
        title: "See the traffic. Understand the next step.",
        text: "Which sources bring interest — and which lead to an enquiry? Crumbs connects traffic, AI referrals, goals and revenue. Saved filters and funnels simplify recurring reports, with an overview across permitted websites.",
        features: [
          "AI referrals, campaign channels and scroll-depth goals",
          "Funnels and source-attributed revenue, by currency",
          "Multi-site overview, Hub permissions and data export",
          "Google Search Console and Data Studio with setup guides",
        ],
        note: "Native collector, no cookies or browser storage. Optional Google connections need your own configuration. No persistent visitor profiles; privacy and capacity remain part of adoption.",
      },
      {
        id: "phone",
        name: "Phone",
        category: "iOS & Android",
        icon: "phone",
        planned: true,
        tabStatus: "Planned",
        status: "PLANNED · NOT YET AVAILABLE",
        illustration: "Concept illustration · planned",
        title: "Your stack. On the go, too.",
        text: "A companion app for iOS and Android is planned: connect your own stack, open the existing web apps and receive and acknowledge incidents directly on your phone.",
        features: [
          "Revocable device authorization for convenient sign-in",
          "Native incident alerts with direct acknowledgement",
          "Alert-readiness check on sign-in and return, with a test alert",
        ],
        note: "Not yet available. Push needs additional infrastructure and platform approvals. Settings changes cannot always be detected immediately; delivery is not guaranteed.",
      },
    ],
    moreTitle: "And a foundation for running it.",
    supporting: [
      [
        "Kitchen",
        "Installation & updates",
        "Installs modules and applies verified releases. After the initial setup, manage apps from the Hub.",
        "layers",
      ],
      [
        "Vault",
        "Snapshots & recovery",
        "Create, schedule and restore snapshots. Per canister — not one atomic backup of the whole suite.",
        "archive",
      ],
      [
        "kebab-mcp",
        "Your AI assistant",
        "Connect your assistant to the apps. It acts with your existing rights; you configure integrations and data flows.",
        "spark",
      ],
      [
        "Ship the Bug",
        "A small break",
        "A game in 2D and 3D. Public play, with optional Hub profiles and opt-in leaderboards.",
        "bug",
      ],
    ],
    engineKicker: "02 / THE TECHNOLOGY, IN PLAIN LANGUAGE",
    engineTitle: "A different foundation.\nA familiar working day.",
    engineIntro:
      "Your team works in a browser. Underneath, kebabstack runs on a Cloud Engine: a configurable execution environment on the Internet Computer.",
    layerLabels: ["YOUR TEAM", "YOUR APPLICATIONS", "YOUR INFRASTRUCTURE"],
    layers: [
      ["Browser", "Sign in. Get things done."],
      ["kebabstack", "Shared Hub. Connected tools."],
      ["Cloud Engine", "Selected nodes run code and store data."],
    ],
    enginePoints: [
      [
        "Cloud Engine",
        "The environment for your apps.",
        "It runs applications across multiple computers, called nodes. Operators and locations depend on your engine configuration.",
      ],
      [
        "Internet Computer (IC / ICP)",
        "The protocol underneath.",
        "It coordinates execution and replication. Your team uses web apps; your IT operators learn the platform and its tools.",
      ],
      [
        "Canister & Motoko",
        "Application logic with persistent state.",
        "A canister holds backend code and stored application data. The Motoko backends need no separate SQL service. Crumbs can collect natively too; external integrations remain explicitly configured services.",
      ],
    ],
    opencloudText:
      "OpenCloud provides a way to provision and manage Cloud Engines. kebabstack is the IT suite that runs on them.",
    opencloudLink: "Meet OpenCloud",
    engineNote:
      "More control comes from deliberate configuration. Review data location, confidentiality from infrastructure operators and external data flows for your environment. The dependency on ICP remains.",
    buildKicker: "03 / YOUR STACK CAN KEEP GROWING",
    buildTitle: "Your workflows are your own.\nYour software can be, too.",
    buildIntro:
      "An extra field. A different approval flow. An entirely new app. Open source and a shared SDK let your team build on what is already there.",
    buildSteps: [
      [
        "01",
        "Adapt",
        "Fork existing apps and shape their interfaces or business logic around the way you work.",
      ],
      [
        "02",
        "Extend",
        "Connect your own app with the SDK: reuse sign-in, the people directory and shared navigation.",
      ],
      [
        "03",
        "Keep building",
        "Write code yourself or work with a coding agent. Review changes, test with data and roll them out deliberately.",
      ],
    ],
    codeLabel: "YOUR STARTING POINT",
    codeComment: "Your idea becomes part of the stack.",
    tree: [
      "Shared sign-in & permissions",
      "Your service workflows",
      "Your devices & assignments",
      "Starting point for your own app",
      "Guide for your team & coding agent",
    ],
    licenseTitle: "MIT. Take it your way.",
    licenseText:
      "The licence permits use, modification and redistribution, including commercially. Keep the copyright and licence notice.",
    licenseLink: "Read the licence",
    buildNote:
      "Motoko helps detect structurally incompatible state changes. Business logic tests, authorization checks, upgrade tests and recovery remain your responsibility.",
    economicsKicker: "04 / THE DECISION",
    economicsTitle: "No fee per seat.\nAn honest total cost.",
    economicsIntro:
      "kebabstack charges no per-person licence fee. Your total cost depends on infrastructure, integrations and the time your team puts in.",
    economicsCards: [
      [
        "01",
        "Shared foundations",
        "A shared directory and sign-in can reduce duplicate integration work.",
      ],
      [
        "02",
        "Fewer separate services",
        "The Motoko backends store data directly in canister state. Crumbs can run without a separate collector. Include additional integrations and their operation in your cost model.",
      ],
      [
        "03",
        "Your own priorities",
        "Source access and application control enable your own extensions. Maintenance, support and updates become your responsibility, too.",
      ],
    ],
    costHeading: "COMPARE THE WHOLE PICTURE",
    costParts: [
      "kebabstack licence",
      "Infrastructure",
      "External APIs",
      "Operating time",
      "Amortized migration",
    ],
    costNote:
      "Operating hours × internal hourly cost; spread migration over an agreed period. Count only subscriptions you can actually cancel. No validated cost or capacity benchmark yet.",
    startKicker: "05 / YOUR NEXT STEP",
    startTitle: "Start small.\nAsk real questions.",
    startIntro:
      "Plan a bounded pilot with test data. Success is not the number of apps installed, but whether your workflows actually work better.",
    pilot: [
      [
        "Define the environment",
        "Agree the engine, responsible IT team, controllers and recovery. Initial setup uses the command line.",
      ],
      [
        "Try a complete workflow",
        "Create five test people, assign a device, approve a request and deactivate a person again.",
      ],
      [
        "Exercise the operation",
        "Test an update, a Hub outage and a restore with sample data. Record time, failures and the external services you still need.",
      ],
    ],
    downloadPilot: "Download the pilot checklist",
    roadmapTitle: "Where things stand.",
    roadmap: [
      [
        "Alpha",
        "The suite, including Crumbs and Desk on-call, is implemented as alpha. For bounded tests and technical evaluation.",
      ],
      [
        "Planned",
        "Phone for iOS and Android: mobile stack access, incident alerts and an alert-readiness check. Not yet available.",
      ],
      [
        "Public source",
        "The complete MIT alpha source on GitHub: apps, SDK, tests, installation guides and design standard.",
      ],
      [
        "Coming soon",
        "OpenCloud Marketplace integration. No marketplace installation path is available yet.",
      ],
    ],
    roadmapNote:
      "Review the source, run the local checks and start a bounded pilot. Manual installation is documented in the public repository.",
    faqTitle: "Good questions. Clear answers.",
    faq: [
      [
        "Does Kebabstack work with OpenSaaS and OpenTeam?",
        "Hub can use OpenTeam as an optional directory source: people and employment status are imported after a reviewed preview, then checked every five minutes. App permissions and Finance stay central in Hub. This alpha connector is locally tested against the directory interface; pilot your specific OpenTeam version before adoption. Shared OpenSaaS sign-in and wider suite integration are not included.",
        "https://github.com/kebabstack/kebabstack-source/blob/main/docs/OPENTEAM.md",
        "Setup and compatibility scope",
      ],
      [
        "Does my team need to understand blockchain or crypto?",
        "For everyday work, they use regular web interfaces. IT operators need platform knowledge for setup and operation. Cloud Engines are operated as infrastructure; employees do not need to buy tokens as part of the app workflow.",
      ],
      [
        "Does kebabstack replace our entire IT landscape?",
        "That depends on your requirements. The suite covers specific jobs, but is not a feature-complete replacement for every IAM, ITSM or endpoint-management product. Email, device management and other external services may still be needed.",
      ],
      [
        "Can we really change the code ourselves?",
        "Yes. The existing MIT licence permits modifications, commercial use and redistribution with the licence notice. The complete alpha is public on GitHub. Included third-party libraries and images retain their own licenses. Backends use Motoko, frontends use web technologies, and the SDK includes an example app.",
      ],
      [
        "Is our data automatically private or hosted in Switzerland?",
        "No. Locations and operators depend on the infrastructure you choose. Replication is not end-to-end encryption against node operators. Identity providers, Slack or AI services can introduce additional data flows. Review them for your specific use.",
      ],
      [
        "How do updates, backups and access revocation work?",
        "Kitchen manages releases; Vault provides per-canister snapshots. There is no atomic suite backup or complete off-site disaster recovery. Bundled apps deny access when directory data reaches 60 seconds without fresh Hub confirmation; upstream identity synchronization adds latency. A Hub outage therefore interrupts app access.",
      ],
      [
        "Is it production-ready?",
        "The current status is alpha. Features are implemented, but cost, capacity and availability have not been established by validated benchmarks. Start with a bounded pilot and decide based on your requirements, testing and operating capacity.",
      ],
    ],
    endTitle: "Ready-made building blocks.\nOpen possibilities.",
    endLink: "Back to the stack",
    footerTag: "The IT suite you can make your own.",
    footerStatus: "Alpha · OpenCloud Marketplace coming soon",
    footerLicense: "MIT licence",
    footerVersion: "Version",
    analyticsPrivacyTitle: "Privacy & Crumbs",
    analyticsPrivacy: "We use our own Crumbs for pageviews, referral sources, active time, scroll depth, link clicks, app selection and downloads. Analytics uses no cookies or browser storage. Do Not Track and Global Privacy Control prevent collection. Your appearance preference is stored only locally, separately from analytics.",
    analyticsProcessing: "The gateway and Cloud Engine process IP addresses and browser information. Crumbs derives daily, site-specific visitor identifiers; raw IP addresses and full browser identifiers are not stored in analytics events. Events leave reports after {days} days and are then progressively deleted. Infrastructure logs and backups have separate retention rules. Product demos still show sample data.",
    footerPrivacy:
      "This site uses no analytics or marketing trackers. Your appearance preference is stored only locally. Infrastructure may process technical access logs.",
    notFound: "This page is not here.",
    backHome: "Back to home",
    theme: "Appearance",
    themeOptions: ["System", "Light", "Dark"],
  },
};
