// Public decision guides. Claims are mapped to implementation in CONTENT.md.
export const guides = [
  {
    id: 'sovereign-it', icon: 'hub', app: 'hub',
    de: {
      path: '/souveraene-it/', title: 'Souveräne IT für KMU auf OpenCloud | Kebabstack',
      heading: 'Mehr Kontrolle über deine IT-Werkzeuge.', label: 'Souveräne IT',
      description: 'Eine verbundene IT-Suite für KMU und Startups auf OpenCloud: zentrale Rechte, Support, Geräte und Verträge. Funktionen, Betrieb und Grenzen der Alpha.',
      intro: 'Wer souveräne IT-Alternativen sucht, braucht mehr als eine neue Hosting-Adresse. Entscheidend ist, wer Zugriffe steuert, wie Daten zwischen Werkzeugen fließen und was das eigene Team selbst ändern kann.',
      sections: [
        ['Was Kebabstack verbindet', 'Hub verwaltet Personen, Anmeldung und App-Rechte. Desk bearbeitet Anfragen, Assets zugewiesene Hardware, Trust den gemeldeten Gerätezustand und Contracts Vertragsentscheidungen. Forms, Watch und Crumbs ergänzen Formulare, Domain-Monitoring und Webanalyse. Der gemeinsame Kontext spart das erneute Zusammensuchen dieser Informationen.'],
        ['OpenCloud als Betriebsgrundlage', 'Kebabstack läuft auf einer Cloud Engine, etwa OpenCloud. Die Anwendungsmodule speichern ihren Zustand in Canistern; für diese Module braucht das Team keinen eigenen SQL-Datenbankserver oder Kubernetes-Cluster. Der optionale Crumbs-Node-Collector hat eine lokale SQLite-Warteschlange. Die Infrastruktur nutzt ICP; Kebabstack ist keine beliebige Docker-Installation.'],
        ['Was souverän hier bedeutet', 'Die MIT-Lizenz erlaubt das Anpassen und Weiterentwickeln des Codes. Betreiber kontrollieren ihre Anwendungs-Canister und deren Controller. Datenstandort, Infrastrukturbetreiber und externe Dienste müssen sie gezielt auswählen und prüfen. Daraus folgt weder automatisch EU-only-Verarbeitung noch Vertraulichkeit gegenüber Infrastrukturbetreibern.'],
        ['Ein gemeinsames Rechtemodell', 'Offizielle Apps übernehmen ihre Rollen aus Hub. Mitarbeitende erhalten eigene und ausdrücklich freigegebene Inhalte, Administratoren die ihnen zugewiesenen Bereiche. Upstream-Änderungen wirken erst, wenn Hub sie erfährt. Die Apps aktualisieren ihre Verzeichnisinformationen und verweigern Zugriffe bei zu alten Informationen; ein Hub-Ausfall kann deshalb die Anmeldung und Arbeit unterbrechen.'],
        ['Welche Kosten bleiben?', 'Kebabstack hat keine eigene Lizenzgebühr pro Person. Cloud-Engine-Infrastruktur, externe APIs, Migration und Betriebszeit bleiben Kostenfaktoren. Ein Pilot sollte messen, welche bestehenden Abonnements wirklich entfallen können und wie viel Routinearbeit das Team tatsächlich spart. Es gibt noch keinen validierten Kapazitäts- oder Kostenbenchmark.'],
      ],
      decision: 'Für wen passt ein Pilot?', decisionText: 'Für kleine IT-Teams, die zusammenhängende Arbeitsabläufe selbst gestalten möchten und eine Alpha bewusst testen können. Wer sofort eine vollständig austauschbare Enterprise-ITSM- oder IAM-Lösung braucht, sollte die benötigten Funktionen zuerst einzeln prüfen.',
      next: 'Den verbundenen Stack ansehen',
    },
    en: {
      path: '/en/sovereign-it/', title: 'Sovereign IT for small teams on OpenCloud | Kebabstack',
      heading: 'More control over your IT tools.', label: 'Sovereign IT',
      description: 'A connected IT suite for startups and SMEs on OpenCloud: shared permissions, support, assets and contracts. Explore the alpha, operating model and limits.',
      intro: 'Sovereign IT takes more than a different hosting address. It matters who controls access, how information moves between tools and what your team can change itself.',
      sections: [
        ['What Kebabstack connects', 'Hub manages people, sign-in and app permissions. Desk handles requests, Assets assigned hardware, Trust reported device posture and Contracts renewal decisions. Forms, Watch and Crumbs add submissions, domain monitoring and web analytics. Shared context reduces the work of finding the same information again.'],
        ['Running on OpenCloud', 'Kebabstack runs on a Cloud Engine such as OpenCloud. Application modules keep their state in canisters, without requiring a separately operated SQL database server or Kubernetes cluster. The optional Crumbs Node collector uses a local SQLite queue. The infrastructure uses ICP; Kebabstack is not a general-purpose Docker installation.'],
        ['What sovereignty means here', 'The MIT license allows teams to adapt and extend the code. Operators control their application canisters and controllers. They still need to choose and review data locations, infrastructure operators and external services. This does not automatically provide EU-only processing or confidentiality from infrastructure operators.'],
        ['One permission model', 'Official apps receive their roles from Hub. Employees see their own and explicitly shared content; administrators see the areas assigned to them. Upstream changes only take effect after Hub learns about them. Apps refresh their directory information and deny access when it becomes too old, so a Hub outage can interrupt sign-in and work.'],
        ['What still costs money?', 'Kebabstack has no per-person license fee of its own. Cloud Engine infrastructure, external APIs, migration and operating time still cost money. A pilot should measure which subscriptions can actually be retired and how much routine work is saved. There is no validated capacity or cost benchmark yet.'],
      ],
      decision: 'Who should consider a pilot?', decisionText: 'Small IT teams that want to shape connected workflows and can deliberately evaluate an alpha. Teams requiring an immediate, complete replacement for enterprise ITSM or IAM should check their required capabilities individually first.',
      next: 'Explore the connected stack',
    },
  },
  {
    id: 'offboarding', icon: 'desk', app: 'desk',
    de: {
      path: '/it-offboarding/', title: 'IT-Offboarding mit Tickets und Hardware-Kontext | Kebabstack Desk',
      heading: 'Ein gesperrter Account darf keine offene Aufgabe verstecken.', label: 'IT-Offboarding',
      description: 'Hub erkennt eine Deaktivierung, Desk eröffnet die Prüfung und Assets liefert Hardware-Kontext. So unterstützt Kebabstack nachvollziehbares IT-Offboarding.',
      intro: 'HR hat kein Ticket erstellt, aber der Account wurde bereits im Identity Provider deaktiviert. Kebabstack verbindet das technische Signal mit einer nachvollziehbaren Aufgabe für die IT.',
      sections: [
        ['1. Die Deaktivierung kommt in Hub an', 'Ein eingerichteter SCIM- oder Verzeichnisabgleich meldet die Änderung einer bekannten Person. Auch eine direkte Deaktivierung in Hub kann den Ablauf auslösen. Voraussetzung ist, dass Hub die Änderung tatsächlich erhält; Kebabstack kann einen unbekannten IdP-Zustand nicht erkennen.'],
        ['2. Desk legt die Prüfung an', 'Bei eingerichtetem Lifecycle-Ablauf entsteht ein Prüfauftrag oder ein vorhandener offener Fall wird wiederverwendet. Eine Sperre ist noch kein Beweis für einen Austritt. Ein Agent klärt, ob die Person austritt oder beispielsweise vorübergehend gesperrt wurde.'],
        ['3. Der Agent sieht den relevanten Kontext', 'Nach Bestätigung des Offboardings und den konfigurierten Freigaben werden zugewiesene Geräte und weitere Hardware aus Assets berücksichtigt. Informationen aus verbundenen Tools folgen deren Berechtigungen. Eine nicht erreichbare Quelle wird als fehlend angezeigt und zählt nicht als erledigt.'],
        ['4. Hardware bekommt ein klares Ergebnis', 'IT plant Rückgabe, Weiterverwendung oder Verkauf. Ein ehemaliger Mitarbeiter kann als externer Käufer einen privaten Dealroom-Link nutzen, während sein Firmenkonto deaktiviert bleibt. Bezahlt bedeutet nicht übergeben: Vorbereitung, Freigabe aus der Geräteverwaltung und physische Übergabe sind eigene Schritte.'],
        ['5. Menschen erledigen die verbleibende Arbeit', 'Kebabstack hilft, offene Schritte sichtbar zu machen und Ergebnisse nachzuhalten. Es löscht nicht automatisch einen Rechner und kündigt keine externen SaaS-Verträge. Externe Accounts, Versand, tatsächliche Gerätevorbereitung und unternehmensspezifische Freigaben müssen weiterhin verantwortlich erledigt werden.'],
      ],
      decision: 'So testest du den Ablauf', decisionText: 'Nimm eine Testperson und ein Testgerät. Prüfe Deaktivierung, vorübergehende Sperre, einen bereits offenen Fall und eine ausgefallene Datenquelle. Kontrolliere anschließend sowohl die Zugriffsrechte als auch die noch offenen Hardware-Aufgaben.',
      next: 'Das Desk-Beispiel durchspielen',
    },
    en: {
      path: '/en/it-offboarding/', title: 'IT offboarding with tickets and asset context | Kebabstack Desk',
      heading: 'A disabled account should not hide unfinished work.', label: 'IT offboarding',
      description: 'Hub detects deactivation, Desk opens a review and Assets supplies hardware context. See how Kebabstack supports accountable IT offboarding.',
      intro: 'HR has not opened a ticket, but the identity provider has already disabled the account. Kebabstack connects that technical signal to a trackable task for IT.',
      sections: [
        ['1. Hub receives the change', 'A configured SCIM or directory connection reports the change for a known person. Direct deactivation in Hub can also trigger the flow. Hub must actually receive the change; Kebabstack cannot detect an unknown identity-provider state.'],
        ['2. Desk opens a review', 'With the lifecycle workflow configured, Desk creates a review or reuses an existing open case. A disabled account does not prove that someone has left. An agent checks whether this is a departure or, for example, a temporary suspension.'],
        ['3. The agent gets relevant context', 'After offboarding is confirmed and configured approvals are satisfied, assigned computers and other hardware from Assets enter the workflow. Information from connected tools follows their permissions. An unavailable source is shown as missing and does not count as complete.'],
        ['4. Hardware gets a clear outcome', 'IT plans return, reuse or sale. A former employee can buy through a private external-buyer dealroom link while their company account stays disabled. Paid does not mean handed over: preparation, release from device management and physical handover are separate steps.'],
        ['5. People finish the remaining work', 'Kebabstack helps surface unfinished tasks and record their outcomes. It does not automatically wipe a computer or cancel external SaaS contracts. External accounts, shipping, actual device preparation and company-specific approvals still need a responsible person.'],
      ],
      decision: 'How to evaluate the flow', decisionText: 'Use a test person and a test device. Check deactivation, temporary suspension, an already open case and an unavailable data source. Then verify both access rights and outstanding hardware tasks.',
      next: 'Walk through the Desk example',
    },
  },
  {
    id: 'analytics', icon: 'crumbs', app: 'crumbs',
    de: {
      path: '/webanalyse-ohne-cookies/', title: 'Webanalyse ohne Cookies auf OpenCloud | Kebabstack Crumbs',
      heading: 'Verstehen, was auf deiner Website funktioniert.', label: 'Analytics ohne Cookies',
      description: 'Crumbs verbindet Webanalyse ohne Cookies mit KI-Quellen, Kampagnen, Scroll-Zielen, Umsatz und Funnels. Für IT-Teams auf OpenCloud, aktuell als Alpha.',
      intro: 'Welche Quellen bringen Besucher? Wo steigen sie aus? Welche Seiten führen zum nächsten Schritt? Crumbs beantwortet diese Fragen im Kebabstack-Stack, ohne Analytics-Cookies oder dauerhafte Besucherkennungen im Browser.',
      sections: [
        ['Quellen, Kampagnen und KI-Verweise', 'Crumbs gruppiert erkennbare Quellen und UTM-Kampagnen. Verweise von unterstützten KI-Diensten wie ChatGPT können als eigener Kanal erscheinen, wenn der Browser einen passenden Referrer übermittelt. Das sind verweisende Dienste, keine Erkennung aller KI-Nutzer oder Crawler. Fehlende Verweise werden nicht erfunden.'],
        ['Vom Seitenaufruf zum Ergebnis', 'Seiten, Scroll-Tiefe und benannte Ereignisse können Ziele bilden. Downloads und externe Links lassen sich automatisch erfassen; eigene Ereignisse und Umsatz benötigen passende Instrumentierung. Funnels zeigen konfigurierte Schritte und Abbrüche, Journeys die beobachteten Wege innerhalb der begrenzten Besuchszuordnung.'],
        ['Ein Bericht, klare Grenzen', 'Gespeicherte Filter, ein Echtzeitfenster und eine gemeinsame Übersicht berechtigter Websites helfen beim täglichen Blick auf die Zahlen. Umsätze bleiben je Währung getrennt. Besucherzahlen sind Schätzungen mit täglich wechselnder Zuordnung und erkennen Menschen nicht dauerhaft über Websites, Tage oder Geräte hinweg.'],
        ['Was ohne Cookies bedeutet', 'Der Tracker verwendet keine Cookies oder Browser-Speicher für Analytics. Er berücksichtigt Do Not Track und Global Privacy Control und minimiert URL- und Referrer-Daten. Deshalb können echte Besuche fehlen, etwa durch Browser-Schutz oder unterdrückte Referrer. Ohne Cookies ist keine pauschale DSGVO-Freigabe: Verarbeitung, Infrastruktur, Rechtsgrundlage und Aufbewahrung bleiben Betreiberentscheidungen.'],
        ['SEO, Exporte und bestehende Werkzeuge', 'Eine optionale Search-Console-Verbindung kann Suchleistung nach ausdrücklicher Google-Anmeldung importieren. Ein bereitgestellter Looker-Studio-Connector benötigt Einrichtung durch den Betreiber. API und Exporte unterstützen eigene Berichte. Eine Verbindung zu Google ist nicht automatisch aktiv.'],
        ['Plausible oder Matomo ersetzen?', 'Crumbs ist eine Alpha mit einem wachsenden Analytics-Umfang, keine nachgewiesene Vollalternative zu allen Funktionen von Plausible oder Matomo. Native Bot-Filter und optionaler Node-Collector haben unterschiedliche Möglichkeiten. Aufbewahrung hat Speicher- und Abfragegrenzen. Prüfe wichtige Berichte, Traffic-Volumen und Datenqualität in einem Pilot, bevor du ein bestehendes Werkzeug abschaltest.'],
      ],
      decision: 'Ein sinnvoller erster Pilot', decisionText: 'Eine Website verbinden, eine konkrete Frage auswählen und ein Ziel definieren. Prüfe reale Seitenaufrufe und Referrer sowie ein eigenes Ereignis. Vergleiche die Definitionen von Besuchen und Besuchern, bevor du Zahlen verschiedener Analytics-Werkzeuge gegeneinander hältst.',
      next: 'Das Crumbs-Beispiel ansehen',
    },
    en: {
      path: '/en/cookieless-analytics/', title: 'Cookieless web analytics on OpenCloud | Kebabstack Crumbs',
      heading: 'Understand what works on your website.', label: 'Cookieless analytics',
      description: 'Crumbs connects cookieless analytics with AI referrals, campaigns, scroll goals, revenue and funnels. Built for IT teams on OpenCloud, currently in alpha.',
      intro: 'Which sources bring visitors? Where do they leave? Which pages lead to the next step? Crumbs helps answer these questions within Kebabstack, without analytics cookies or persistent visitor identifiers in the browser.',
      sections: [
        ['Sources, campaigns and AI referrals', 'Crumbs groups recognized sources and UTM campaigns. Referrals from supported AI services such as ChatGPT can appear as a channel when the browser supplies a matching referrer. These are referring services, not detection of all AI users or crawlers. Missing referrals are not invented.'],
        ['From a pageview to an outcome', 'Pages, scroll depth and named events can become goals. Downloads and outbound links can be collected automatically; custom events and revenue need suitable instrumentation. Funnels show configured steps and drop-off, while journeys show observed paths within the limited visit association.'],
        ['One report, explicit boundaries', 'Saved filters, a realtime window and a combined view of permitted websites help with daily reporting. Revenue stays separate by currency. Visitor counts are estimates with daily rotation, not persistent identification of people across websites, days or devices.'],
        ['What cookieless means', 'The tracker uses no cookies or browser storage for analytics. It respects Do Not Track and Global Privacy Control and minimizes URL and referrer data. Real visits can therefore be missing, for example because of browser protection or suppressed referrers. Cookieless does not mean automatic GDPR approval: processing, infrastructure, legal basis and retention remain operator decisions.'],
        ['SEO, exports and existing tools', 'An optional Search Console connection can import search performance after an explicit Google sign-in. The supplied Looker Studio connector requires operator setup. An API and exports support custom reports. A Google connection is not enabled automatically.'],
        ['Replacing Plausible or Matomo?', 'Crumbs is an alpha with growing analytics coverage, not a demonstrated complete alternative to every Plausible or Matomo feature. Native bot filtering and the optional Node collector have different capabilities. Retention has storage and query limits. Evaluate required reports, traffic volume and data quality before retiring an existing tool.'],
      ],
      decision: 'A useful first pilot', decisionText: 'Connect one website, choose a concrete question and define one goal. Verify real pageviews and referrers plus a custom event. Compare how visits and visitors are defined before comparing numbers between analytics tools.',
      next: 'Explore the Crumbs example',
    },
  },
];
