import assert from 'node:assert/strict';
import {test,before,after} from 'node:test';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {resolve} from 'node:path';
import {PocketIc,PocketIcServer,createIdentity} from '@dfinity/pic';
const p=Object.fromEntries(['controller','owner','second','employee','lunch'].map(n=>[n,createIdentity('display-'+n).getPrincipal()]));
const hash=s=>createHash('sha256').update(s).digest('hex');
const dir=m=>process.env.KEBAB_DISPLAY_CANDIDATE?resolve(process.env.KEBAB_DISPLAY_CANDIDATE,m):resolve(m,'backend/dist');
async function idl(path){return(await import('data:text/javascript;base64,'+Buffer.from(execFileSync('python3',['sdk/tools/did2idl.py',path],{encoding:'utf8'})).toString('base64'))).idlFactory;}
let server;before(async()=>{server=await PocketIcServer.start();});after(async()=>{await server?.stop();});
async function install(pic,m,baseline=false){const d=baseline?process.env.KEBAB_DISPLAY_BASELINE:dir(m);return pic.setupCanister({sender:p.controller,controllers:[p.controller],wasm:d+'/backend.wasm',idlFactory:await idl(d+'/backend.did'),environmentVariables:m==='hub'?[{name:'KEBAB_CLAIM_CODE',value:'bc'.repeat(32)}]:[]});}
async function setup(pic,baseline=false){await pic.setTime(new Date('2026-09-18T12:00:00Z'));const h=await install(pic,'hub',baseline);let hub=h.actor;hub.setPrincipal(p.owner);assert.ok((await hub.claimHubWithCode('bc'.repeat(32),{email:'owner@display.test',displayName:'PRIVATE OWNER',orgName:'Display test'})).ok);for(const n of ['second','employee']){assert.ok(await hub.addLocalUser(n+'@display.test',n,'',''));const[code]=await hub.createInvite(n+'@display.test');hub.setPrincipal(p[n]);assert.ok(await hub.claimInvite(code));hub.setPrincipal(p.owner);}assert.ok((await hub.setPersonRole('second@display.test','owner')).ok);await pic.tick(2);
 const a=await install(pic,'assets');a.actor.setPrincipal(p.controller);await a.actor.setHub(h.canisterId.toText());const c=await hub.connectApp({name:'PRIVATE INVENTORY',canisterId:a.canisterId.toText(),note:'',lanes:['identity','profile','groups'],access:{mode:'everyone',groups:[],roles:[],people:[]},tile:[{name:'PRIVATE APP NAME',kind:'app',url:'https://assets.display.test'}]});assert.ok(c.ok);const [v]=await hub.getAppPermissions(c.id);assert.ok((await hub.setAppPermissions(c.id,v.revision,{app:'assets',defaultRole:'member',people:[],groups:[]})).ok);const ticket=await hub.mintAppTicket('',c.tileId);const[t]=await a.actor.loginWithTicket(ticket.ticket);assert.ok(t);assert.ok((await a.actor.intakeCommit(t.token,{assetId:[],create:[{tag:'PRIVATE TAG',serial:'PRIVATE SERIAL',vendor:'Example',model:'Monitor',kind:'monitor',note:''}],action:'returned',to:'',note:'',photo:[],mime:''})).ok);
 assert.ok((await hub.connectApp({name:'Lunch',canisterId:p.lunch.toText(),note:'',lanes:['identity'],access:{mode:'everyone',groups:[],roles:[],people:[]},tile:[]})).ok);hub.setPrincipal(p.lunch);const lunch=await hub.team_members();hub.setPrincipal(p.owner);
 if(baseline){await pic.upgradeCanister({sender:p.controller,canisterId:h.canisterId,wasm:dir('hub')+'/backend.wasm',upgradeModeOptions:{skip_pre_upgrade:[],wasm_memory_persistence:[{keep:null}]}});hub=pic.createActor(await idl(dir('hub')+'/backend.did'),h.canisterId);hub.setPrincipal(p.owner);}
 const anon=pic.createActor(await idl(dir('hub')+'/backend.did'),h.canisterId);
 return{h,hub,anon,a,c,lunch};}
async function pair(f,secret,code='a1234b5678',days=7n){assert.ok('ok' in await f.anon.operationsDisplayPair(code,hash(secret)));f.hub.setPrincipal(p.owner);const r=await f.hub.operationsDisplayApprove(code,'IT room',[f.c.id],days);assert.ok('ok' in r,JSON.stringify(r,(_,v)=>typeof v==='bigint'?String(v):v));return r.ok;}
for(const baseline of [false,true])test(`Displays: ${baseline?'upgrade from Operations 0.28':'fresh install'} isolates capabilities, preserves Lunch and survives upgrade`,{skip:baseline&&!process.env.KEBAB_DISPLAY_BASELINE},async()=>{
 const pic=await PocketIc.create(server.getUrl());try{const f=await setup(pic,baseline),secret='12'.repeat(32);f.hub.setPrincipal(p.owner);assert.equal((await f.hub.operationsDisplayAdmin()).canManage,true);f.hub.setPrincipal(p.employee);assert.equal((await f.hub.operationsDisplayAdmin()).canManage,false);assert.ok('denied' in await f.hub.operationsDisplayApprove('a1234b5678','forged',[f.c.id],7n));assert.ok('denied' in await f.anon.operationsDisplayApprove('a1234b5678','forged',[f.c.id],7n));
 assert.ok('invalid' in await f.anon.operationsDisplayPair('bad',hash(secret)));assert.ok('ok' in await f.anon.operationsDisplayPair('a1234b5678',hash(secret)));assert.ok('busy' in await f.anon.operationsDisplayPair('a1234b5678',hash('34'.repeat(32))));assert.ok('pending' in await f.anon.operationsDisplayState(secret));assert.ok('denied' in (await f.anon.operationsDisplaySnapshot(secret,f.c.id)).state);
 f.hub.setPrincipal(p.owner);assert.ok('invalid' in await f.hub.operationsDisplayApprove('a1234b5678','IT room',[f.c.id,f.c.id],7n));assert.ok('invalid' in await f.hub.operationsDisplayApprove('a1234b5678','IT room',[f.c.id],365n));const id=await pair(f,secret);assert.ok('missing' in await f.hub.operationsDisplayApprove('a1234b5678','replay',[f.c.id],7n));
 const state=await f.anon.operationsDisplayState(secret);assert.equal(state.ready.sources[0].app,'assets');assert.doesNotMatch(JSON.stringify(state,(_,v)=>typeof v==='bigint'?String(v):v),/PRIVATE|@|canisterId|by|personId/);assert.ok('ended' in await f.anon.operationsDisplayState(hash(secret)),'stored hash is not a credential');assert.ok('denied' in (await f.anon.operationsDisplaySnapshot(secret,999n)).state);
 f.hub.setPrincipal(p.owner);assert.ok((await f.hub.checkAppPermissions(f.c.id)).ok);let data=await f.anon.operationsDisplaySnapshot(secret,f.c.id);assert.ok('ready' in data.state);assert.deepEqual(Object.keys(Object.fromEntries(data.metrics)).sort(),['assigned','preparing','stock','total']);assert.equal(Object.fromEntries(data.metrics).stock,1n);assert.ok('unavailable' in (await f.anon.operationsDisplaySnapshot(secret,f.c.id)).state,'expensive calls throttled');
 // The display token is not a user session and grants no general reads or mutations.
 await assert.rejects(()=>f.anon.operationsSources());assert.ok('denied' in (await f.anon.operationsSnapshot(f.c.id)).state);assert.equal((await f.anon.suiteState(secret)).length,0);assert.equal(await f.anon.operationsDisplayRevoke(id),false);
 await pic.upgradeCanister({sender:p.controller,canisterId:f.h.canisterId,wasm:dir('hub')+'/backend.wasm',upgradeModeOptions:{skip_pre_upgrade:[],wasm_memory_persistence:[{keep:null}]}});assert.ok('ready' in await f.anon.operationsDisplayState(secret),'approved display survives upgrade');f.hub.setPrincipal(p.lunch);assert.deepEqual(await f.hub.team_members(),f.lunch);f.hub.setPrincipal(p.owner);
 // Renames preserve the stable person binding. Loss of Owner rights suspends it.
 assert.ok((await f.hub.renameLocalUser('owner@display.test','renamed@display.test')).ok);assert.ok('ready' in await f.anon.operationsDisplayState(secret));f.hub.setPrincipal(p.second);assert.ok((await f.hub.setPersonRole('renamed@display.test','admin')).ok);assert.ok('ended' in await f.anon.operationsDisplayState(secret));assert.ok('denied' in (await f.anon.operationsDisplaySnapshot(secret,f.c.id)).state);assert.ok(await f.hub.operationsDisplayRevoke(id));assert.ok('ended' in await f.anon.operationsDisplayState(secret));assert.ok((await f.hub.setPersonRole('renamed@display.test','owner')).ok);assert.ok('ended' in await f.anon.operationsDisplayState(secret),'revocation cannot revive');
 // Deactivation stops a paired screen even if its previous app cache is fresh.
 await pair(f,'78'.repeat(32),'987654abcd',7n);f.hub.setPrincipal(p.second);
 const people=await f.hub.listUsers({search:'renamed@display.test',offset:0n,limit:10n,conn:[],activeOnly:false});const owner=people.items.find(u=>u.email==='renamed@display.test');assert.ok(owner);
 assert.ok(await f.hub.deactivateUser(owner.key,'Test departure'));assert.ok('ended' in await f.anon.operationsDisplayState('78'.repeat(32)));assert.ok('denied' in (await f.anon.operationsDisplaySnapshot('78'.repeat(32),f.c.id)).state);
 assert.ok(await f.hub.clearOverride(owner.key));await f.anon.operationsDisplayForget('78'.repeat(32));

 // Re-pair, and expire without an owner/browser renewal action.
 await pair(f,'56'.repeat(32),'123456abcd',1n);await pic.advanceTime(86400001);assert.ok('ended' in await f.anon.operationsDisplayState('56'.repeat(32)));assert.ok('denied' in (await f.anon.operationsDisplaySnapshot('56'.repeat(32),f.c.id)).state);
 }finally{await pic.tearDown();}
});
test('Displays: bounded pairing, proof-only disconnect and abandoned-code expiry',async()=>{const pic=await PocketIc.create(server.getUrl());try{const f=await setup(pic);const secret='aa'.repeat(32);await pair(f,secret);await f.anon.operationsDisplayForget('bb'.repeat(32));assert.ok('ready' in await f.anon.operationsDisplayState(secret));await f.anon.operationsDisplayForget(secret);assert.ok('ended' in await f.anon.operationsDisplayState(secret));for(let i=0;i<11;i++)assert.ok('ok' in await f.anon.operationsDisplayPair(i.toString(16).padStart(10,'0'),hash('random-'+i)));assert.ok('busy' in await f.anon.operationsDisplayPair('eeeeeeeeee',hash('overflow')));await pic.advanceTime(600001);f.hub.setPrincipal(p.owner);assert.ok('missing' in await f.hub.operationsDisplayApprove('0000000000','late',[f.c.id],7n));assert.ok('ok' in await f.anon.operationsDisplayPair('eeeeeeeeee',hash('new')));}finally{await pic.tearDown();}});
