import{test}from'node:test';import assert from'node:assert/strict';import{mkdtemp,mkdir,writeFile,rm}from'node:fs/promises';import{tmpdir}from'node:os';import{resolve}from'node:path';import{Principal}from'@icp-sdk/core/principal';import{bundleFiles,publish,sha}from'../kitchen/tools/release.mjs';
async function bundle(){const dir=await mkdtemp(resolve(tmpdir(),'release-publisher-')),content=Buffer.from('verified wasm'),hash=sha(content),prefix='test/1.0.0/'+'a'.repeat(64);await mkdir(resolve(dir,prefix),{recursive:true});await writeFile(resolve(dir,prefix,'backend.wasm'),content);const index={format:2,recipes:[{id:'test',version:'1.0.0',releaseId:'a'.repeat(64),sourceCommit:'b'.repeat(40),backend:{path:'recipes/'+prefix+'/backend.wasm',sha256:hash,size:content.length},frontend:{files:[]}}]};const save=()=>writeFile(resolve(dir,'index.json'),JSON.stringify(index));await save();return{dir,index,save,close:()=>rm(dir,{recursive:true,force:true})};}
function mock({collision=false,failChunk=false}={}){const events=[],files=new Map(),chunks=new Map();let next=0;const operator=Principal.fromText('aaaaa-aa');const call=async(id,method,args=[])=>{events.push(method);if(method==='info')return{pantryId:'source'};if(method==='listJobs')return[];if(method==='list'){const start=Number(args[0].start?.[0]??0),length=Math.min(Number(args[0].length?.[0]??100),100);return[...files.values()].sort((a,b)=>a.key<b.key?-1:1).slice(start,start+length);}if(method==='list_permitted')return[];if(method==='create_batch')return{batch_id:1n};if(method==='create_chunk'){if(failChunk)throw Error('upload failed');chunks.set(++next,args[0].content);return{chunk_id:BigInt(next)};}if(method==='commit_batch'){for(const o of args[0].operations){if(o.CreateAsset){const a=o.CreateAsset;if(files.has(a.key))throw Error('asset already exists');files.set(a.key,{...a,encodings:[]});}if(o.SetAssetContent){const a=o.SetAssetContent,old=files.get(a.key);old.encodings=[{content_encoding:'identity',sha256:a.sha256}];}}}return[];};return{kitchen:'installer',cli:async()=>operator.toText(),call,events,files};}
test('publication activates the catalogue atomically and retains existing packages',async()=>{const b=await bundle(),api=mock();try{api.files.set('/recipes/old/backend.wasm',{key:'/recipes/old/backend.wasm',content_type:'application/wasm',encodings:[]});const r=await publish(api,b.dir,{log:()=>{}});assert.equal(r.published,true);assert.ok(api.files.has('/recipes/index.json'));assert.ok(api.files.has('/recipes/old/backend.wasm'));assert.equal(api.events.filter(x=>x==='commit_batch').length,1);assert.equal(api.events.filter(x=>x==='revoke_permission').length,2);const again=await publish(api,b.dir,{log:()=>{}});assert.equal(again.published,false);}finally{await b.close();}});
test('failed upload cannot activate a partial catalogue and temporary rights are restored',async()=>{const b=await bundle(),api=mock({failChunk:true});try{await assert.rejects(publish(api,b.dir,{log:()=>{}}),/upload failed/);assert.equal(api.events.includes('commit_batch'),false);assert.equal(api.events.includes('delete_batch'),true);assert.equal(api.events.filter(x=>x==='revoke_permission').length,2);assert.equal(api.files.has('/recipes/index.json'),false);}finally{await b.close();}});
test('corruption, traversal and immutable collisions are refused before any write',async()=>{const b=await bundle(),api=mock();try{const f=(await bundleFiles(b.dir)).files[0];api.files.set(f.key,{key:f.key,content_type:f.type,encodings:[{content_encoding:'identity',sha256:[Buffer.alloc(32)]}]});await assert.rejects(publish(api,b.dir),/Immutable release/);assert.deepEqual(api.events,['info','list']);b.index.recipes[0].backend.sha256='c'.repeat(64);await b.save();await assert.rejects(bundleFiles(b.dir),/checksum/);b.index.recipes[0].backend.path='../escape';await b.save();await assert.rejects(bundleFiles(b.dir),/immutable/);}finally{await b.close();}});

test('compressed assets must decode to the exact identity representation before publication',async()=>{const b=await bundle();try{const {gzipSync}=await import('node:zlib');const r=b.index.recipes[0],prefix=r.backend.path.slice(0,-'backend.wasm'.length),raw=Buffer.from('Shared login runtime '.repeat(100)),compressed=gzipSync(raw);await mkdir(resolve(b.dir,prefix.slice(8),'frontend'),{recursive:true});await mkdir(resolve(b.dir,prefix.slice(8),'frontend.gzip'),{recursive:true});await writeFile(resolve(b.dir,prefix.slice(8),'frontend/shared.js'),raw);await writeFile(resolve(b.dir,prefix.slice(8),'frontend.gzip/shared.js'),compressed);r.frontend={wasm:r.backend.path,sha256:r.backend.sha256,dir:prefix+'frontend',files:[{key:'/shared.js',type:'text/javascript',sha256:sha(raw),size:raw.length,gzip:{sha256:sha(compressed),size:compressed.length}}],patch:[]};await b.save();await bundleFiles(b.dir);const wrong=gzipSync(Buffer.from('stale code'));await writeFile(resolve(b.dir,prefix.slice(8),'frontend.gzip/shared.js'),wrong);r.frontend.files[0].gzip={sha256:sha(wrong),size:wrong.length};await b.save();await assert.rejects(bundleFiles(b.dir),/does not match the release/);}finally{await b.close();}});

test('publication reads past the first 100 stored files, including an existing catalogue and immutable collisions',async()=>{
 const b=await bundle(),api=mock();try{
  for(let i=0;i<205;i++)api.files.set('/archive/'+String(i).padStart(4,'0'),{key:'/archive/'+String(i).padStart(4,'0'),content_type:'text/plain',encodings:[]});
  api.files.set('/recipes/index.json',{key:'/recipes/index.json',content_type:'application/json',encodings:[{content_encoding:'identity',sha256:[Buffer.alloc(32)]}]});
  assert.equal((await publish(api,b.dir,{log:()=>{}})).published,true);assert.equal(api.files.size,207);
  assert.equal((await publish(api,b.dir,{log:()=>{}})).published,false);
  const file=(await bundleFiles(b.dir)).files[0];api.files.get(file.key).encodings[0].sha256=[Buffer.alloc(32)];
  const writes=api.events.filter(x=>x==='create_batch').length;await assert.rejects(publish(api,b.dir,{log:()=>{}}),/Immutable release/);assert.equal(api.events.filter(x=>x==='create_batch').length,writes);
 }finally{await b.close();}
});
