export const person={id:'p_owner',email:'owner@example.test',displayName:'Taylor Morgan',role:'admin'};
export const metric={visitors:4286n,visits:5032n,pageviews:12648n,events:612n,bounces:1857n,durationSeconds:1011432n,engagementMs:144000000n,scrollDepthSum:73500n,scrollSamples:1000n,revenue:[['CHF',245000n]]};
export function fixture({role='admin',empty=false,unsafe=false}={}){
 let sites=empty?[]:[{id:'example',name:'Example website',domain:'example.test',timezone:'UTC',retentionDays:365n,enabled:true,allowedProperties:['plan'],excludedPaths:[],viewers:[]}];const calls=[];let invalid=false,fail=false,siteRole=role==='admin'?'admin':role==='manager'?'manage':'read';let access={site:'example',revision:1n,readers:[],managers:[],legacyAllReaders:false,updatedBy:'p_owner',updatedAt:0n};const people=[{id:'p_casey',email:'casey@example.test',displayName:unsafe?'<img src=x onerror=alert(1)>':'Casey Adams',active:true,eligible:true,automatic:false},{id:'p_jordan',email:'jordan@example.test',displayName:'Jordan Lee',active:true,eligible:true,automatic:false},{id:person.id,email:person.email,displayName:person.displayName,active:true,eligible:true,automatic:true}];
 let saved=[],connection={clientId:'',property:'',revision:0n},snapshot=[];
 const actor={
  savedReports:async()=>({ok:saved}),saveReport:async(t,r)=>{calls.push(['saveReport',r]);saved.push({...r,revision:1n});return {ok:r};},deleteReport:async(t,s,id)=>{saved=saved.filter(r=>r.id!==id);return {ok:null};},
  goalReport:async()=>({ok:{visitors:246n,completions:290n,revenue:[['CHF',245000n]]}}),searchConnection:async()=>({ok:connection}),saveSearchConnection:async(t,s,c)=>{connection={...c,revision:c.revision+1n};return {ok:connection};},searchSnapshot:async()=>({ok:snapshot}),saveSearchSnapshot:async(t,r,s)=>{snapshot=[{...s,fetchedAt:BigInt(Math.floor(Date.now()/1000))}];return {ok:null};},
  listSites:async()=>sites.map(s=>({...s,accessRole:{[siteRole]:null}})),whoami:async()=>invalid?[]:[{...person,role:role==='manager'?'viewer':role}],signOut:async()=>{},
  getSiteAccess:async()=>({ok:access}),accessPeople:async(t,s,q)=>({ok:{people:people.filter(p=>(p.email+p.displayName).toLowerCase().includes(q.toLowerCase())),truncated:false}}),setSiteAccess:async(t,s,revision,readers,managers)=>{calls.push(['setSiteAccess',{s,revision,readers,managers}]);if(revision!==access.revision)return {err:{conflict:'Website access changed. Reload before saving.'}};access={...access,site:s,revision:revision+1n,readers:readers.map(id=>people.find(p=>p.id===id)),managers:managers.map(id=>people.find(p=>p.id===id))};return {ok:access};},
  saveSite:async(t,s)=>{calls.push(['saveSite',s]);sites=sites.filter(x=>x.id!==s.id).concat(s);return {ok:s};},
  deleteSite:async(t,id)=>{sites=sites.filter(x=>x.id!==id);return {ok:null};},
  report:async(t,r)=>{calls.push(['report',r]);if(fail)return {err:{capacity:'Report exceeds tested capacity'}};
   const dimensions={channel:['Organic search','AI assistants','Paid search','Direct / unknown'],aiSource:['ChatGPT','Perplexity','Claude'],path:['/','/pricing','/docs',unsafe?'/<img src=x onerror=alert(1)>':'/blog'],source:['Google','Direct / none','github.com','newsletter'],country:['CH','DE','US','GB'],device:['Desktop','Mobile','Tablet'],campaign:['September launch','Product newsletter','Partner referrals'],entryPath:['/','/pricing'],exitPath:['/docs','/pricing']};
   let rows=(dimensions[r.dimension]??[]).map((v,i)=>({value:v,metrics:{...Object.fromEntries(Object.entries(metric).filter(([key])=>key!=='revenue').map(([key,value])=>[key,key==='visitors'?BigInt([2152,1194,620,320][i]):BigInt(Math.round(Number(value)*[0.5,0.28,0.145,0.075][i]))])),revenue:metric.revenue.map(([currency,value])=>[currency,BigInt(Math.round(Number(value)*[0.5,0.28,0.145,0.075][i]))])}}));
   if(['day','hour','minute'].includes(r.dimension)){rows=[];for(let at=Number(r.from),i=0;at<Number(r.until);at+=r.dimension==='minute'?60:r.dimension==='hour'?3600:86400,i++)rows.push({value:String(at),metrics:{...metric,visitors:BigInt(Math.round(80+i*3+30*Math.sin(i*1.8)))}});}
   return {ok:{totals:metric,rows,scanned:13260n,truncated:false}};},
  goals:async()=>({ok:[{id:'signup',site:'example',name:'Signup',kind:{event:null},value:'Signup'}]}),saveGoal:async(t,g)=>{calls.push(['saveGoal',g]);return {ok:null};},deleteGoal:async()=>({ok:null}),
  funnel:async(t,r,steps)=>({ok:[100n,42n,19n].slice(0,steps.length)}),journeys:async()=>({ok:[['(entry)','/',520n],['/','/pricing',248n],['/pricing','/signup',104n]]}),
  imported:async()=>({ok:[]}),listKeys:async()=>({ok:[]}),createKey:async()=>({ok:{token:'1'.repeat(64),key:{id:'one'}}}),revokeKey:async()=>({ok:null}),
  health:async()=>({ok:{accepted:13260n,duplicates:14n,rejected:0n,storedEvents:13260n,collectors:['example'],storageChargeBytes:20000000n}}),exportEvents:async()=>({ok:{events:[],cursor:''}})
 };
 return {actor,calls,demote:()=>{siteRole='read';},invalidate:()=>{invalid=true;},fail:()=>{fail=true;}};
}
