import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {JSDOM} from 'jsdom';
const script=readFileSync(new URL('../dist/tracker.js',import.meta.url),'utf8');
function browser({consent=false,privacy=false,hash=false,url='https://example.test/start',referrer=''}={}){
 const dom=new JSDOM('<body><button data-crumbs-event="Signup">Join</button><a href="https://external.test/">External</a><script src="https://analytics.test/tracker.js" data-site="main" data-outbound="true"'+(hash?' data-hash="true"':'')+'></script></body>',{url,referrer:referrer||undefined,runScripts:'outside-only',pretendToBeVisual:true});
 const {window:w}=dom;Object.defineProperty(w.document,'currentScript',{value:w.document.querySelector('script')});w.crypto.randomUUID=randomUUID;w.crumbsConsentRequired=consent;if(privacy)Object.defineProperty(w.navigator,'globalPrivacyControl',{value:true});
 const sent=[],beacons=[];w.fetch=async(url,options)=>{sent.push(...JSON.parse(options.body));return {ok:true,status:202};};w.navigator.sendBeacon=(url,body)=>{beacons.push(body);return true;};w.eval(script);
 return {dom,w,sent,beacons};
}
const settle=()=>new Promise(resolve=>setTimeout(resolve,20));
test('tracker counts page loads and SPA paths once, emits custom button events and never writes browser storage',async()=>{const {dom,w,sent}=browser();try{await settle();assert.equal(sent.filter(e=>e.kind==='pageview').length,1);w.history.pushState({},'','/pricing');await settle();w.history.replaceState({},'','/pricing');await settle();assert.equal(sent.filter(e=>e.kind==='pageview').length,2);w.document.querySelector('button').click();await settle();assert.ok(sent.some(e=>e.name==='Signup'));assert.equal(w.document.cookie,'');assert.equal(w.localStorage.length,0);assert.equal(w.sessionStorage.length,0);assert.ok(sent.every(e=>!('visitor'in e)&&!('ip'in e)));w.eval(script);await settle();assert.equal(sent.filter(e=>e.kind==='pageview').length,2);}finally{dom.window.close();}});
test('tracker gates consent, clears queued events on withdrawal and respects privacy signals on resume',async()=>{let b=browser({consent:true});try{await settle();assert.equal(b.sent.length,0);b.w.crumbsConsentGranted=true;b.w.crumbs.resume();await settle();assert.equal(b.sent.filter(e=>e.kind==='pageview').length,1);b.w.crumbsConsentGranted=false;b.w.crumbs.pause();b.w.crumbs('Secret');await settle();assert.equal(b.sent.some(e=>e.name==='Secret'),false);}finally{b.dom.window.close();}b=browser({privacy:true});try{b.w.crumbs.resume();b.w.crumbs('ShouldNotSend');await settle();assert.equal(b.sent.length,0);}finally{b.dom.window.close();}});
test('hash routing is explicit and route fragments become sanitized page paths',async()=>{const b=browser({hash:true});try{await settle();b.w.history.pushState({},'','/#/pricing');await settle();assert.equal(b.sent.filter(e=>e.kind==='pageview').at(-1).url,'https://example.test/pricing');}finally{b.dom.window.close();}});

test('consent withdrawal and resume during an in-flight request cannot discard the new pageview',async()=>{
 const b=browser();try{await settle();let release;const sent=[];b.w.fetch=async(url,options)=>{sent.push(...JSON.parse(options.body));if(sent.length===1)await new Promise(r=>{release=r;});return {ok:true,status:202};};
 b.w.crumbs('BeforeWithdrawal');await settle();b.w.crumbs.pause();b.w.crumbs.resume();release();await settle();assert.ok(sent.some(e=>e.name==='BeforeWithdrawal'));assert.equal(sent.filter(e=>e.kind==='pageview').length,1);
 }finally{b.dom.window.close();}
});

test('tracker removes non-campaign secrets before transport, including the first referrer',async()=>{const b=browser({url:'https://example.test/person/alice%40example.test/123456?token=secret&utm_source=chatgpt.com&utm_campaign=alice%40example.test#secret',referrer:'https://external.test/private?token=hidden'});try{await settle();const p=b.sent.find(e=>e.kind==='pageview');assert.equal(p.referrer,'https://external.test');assert.doesNotMatch(p.url,/alice|123456|token|secret|%40/);assert.match(p.url,/utm_source=chatgpt.com/);assert.equal(b.w.crumbs.status().lastDelivery,'accepted');b.w.history.pushState({},'','/pricing');await settle();assert.equal(b.sent.filter(e=>e.kind==='pageview').at(-1).referrer,'https://example.test');}finally{b.dom.window.close();}});
test('tracker diagnoses privacy and rejected delivery, and BFCache return creates a new pageview',async()=>{const b=browser();try{await settle();b.w.fetch=async()=>({ok:false,status:400});b.w.crumbs('Bad');await settle();assert.equal(b.w.crumbs.status().lastDelivery,'rejected');assert.equal(b.w.crumbs.status().pending,0);b.w.fetch=async(u,o)=>{b.sent.push(...JSON.parse(o.body));return {ok:true,json:async()=>({accepted:0,duplicates:0,ignored:1})};};b.w.dispatchEvent(new b.w.PageTransitionEvent('pageshow',{persisted:true}));await settle();assert.equal(b.sent.filter(e=>e.kind==='pageview').length,2);assert.equal(b.w.crumbs.status().lastDelivery,'ignored');Object.defineProperty(b.w.navigator,'globalPrivacyControl',{value:true});assert.equal(b.w.crumbs.status().state,'privacy-signal');}finally{b.dom.window.close();}});
test('tracker remains below its documented compressed budget',async()=>{const {gzipSync}=await import('node:zlib');assert.ok(gzipSync(script).length<5000,'tracker gzip budget is 5 KiB');});
