import assert from 'node:assert/strict';
import {test} from 'node:test';
import {readFileSync} from 'node:fs';
import {webcrypto} from 'node:crypto';
import {JSDOM} from 'jsdom';
const code=readFileSync(new URL('../dist/displays.js',import.meta.url),'utf8');
const tick=()=>new Promise(r=>setTimeout(r,0));
const nano=x=>BigInt(x)*1000000n;
function fixture(api,options={}){const dom=new JSDOM('<main></main>',{runScripts:'outside-only',pretendToBeVisual:true,url:'https://hub.test/#/tv'}),w=dom.window;Object.defineProperty(w,'crypto',{value:webcrypto});w.TextEncoder=TextEncoder;w.eval(code);const root=w.document.querySelector('main');w.localStorage.setItem('ks-operations-display-v1',JSON.stringify({secret:'12'.repeat(32),code:'abcde12345'}));const ui=w.KebabDisplays.createTV(root,api,{pollInterval:999999,...options});return{w,root,ui,close(){ui.destroy();w.close();}};}
const ready=(at=Date.now())=>({ready:{id:1n,name:'Team room <script>',expiresAt:nano(at+86400000),checkedAt:nano(at),sources:[{cid:1n,app:'assets'}]}});
const snapshot=(at=Date.now())=>({schema:1n,state:{ready:null},checkedAt:nano(at),metrics:[['total',34n],['stock',14n],['assigned',20n],['preparing',2n]]});
test('TV shows approved numeric data without app links, personal fields or a user session',async()=>{const f=fixture({operationsDisplayState:async()=>ready(),operationsDisplaySnapshot:async()=>snapshot()});try{await tick();await tick();assert.match(f.root.textContent,/14/);assert.match(f.root.textContent,/Team room <script>/);assert.equal(f.root.querySelectorAll('script,a').length,0);assert.match(f.root.textContent,/1 of 1 approved sources checked/);assert.doesNotMatch(f.root.textContent,/sales|offboarding|PRIVATE/);}finally{f.close();}});
test('revocation removes all data and a late source response cannot restore it',async()=>{let resolve,approved=true;const f=fixture({operationsDisplayState:async()=>approved?ready():{ended:null},operationsDisplaySnapshot:()=>new Promise(r=>resolve=r)});try{await tick();approved=false;await f.ui.check();resolve(snapshot());await tick();assert.match(f.root.textContent,/no longer approved/);assert.equal(f.root.querySelectorAll('.tv-number').length,0);}finally{f.close();}});
test('a hidden or disconnected screen discards totals and requires fresh approval',async()=>{let failed=false;const f=fixture({operationsDisplayState:async()=>{if(failed)throw Error();return ready();},operationsDisplaySnapshot:async()=>snapshot()});try{await tick();await tick();assert.equal(f.root.querySelectorAll('.tv-number').length,1);Object.defineProperty(f.w.document,'hidden',{value:true,configurable:true});f.w.document.dispatchEvent(new f.w.Event('visibilitychange'));assert.equal(f.root.querySelectorAll('.tv-number').length,0);Object.defineProperty(f.w.document,'hidden',{value:false,configurable:true});failed=true;f.w.document.dispatchEvent(new f.w.Event('visibilitychange'));await tick();assert.match(f.root.textContent,/Connection paused/);}finally{f.close();}});
test('stale access, malformed metrics and additional fields never render as healthy',async()=>{let at=Date.now();const f=fixture({operationsDisplayState:async()=>ready(at-31000),operationsDisplaySnapshot:async()=>snapshot()},{now:()=>at});try{await tick();assert.match(f.root.textContent,/Connection paused/);}finally{f.close();}const g=fixture({operationsDisplayState:async()=>ready(),operationsDisplaySnapshot:async()=>({...snapshot(),metrics:[...snapshot().metrics,['sales',91n]]})});try{await tick();await tick();assert.match(g.root.textContent,/Source unverified/);assert.doesNotMatch(g.root.textContent,/91/);}finally{g.close();}});
test('disconnect removes the credential before the backend responds',async()=>{let finish;const f=fixture({operationsDisplayState:async()=>ready(),operationsDisplaySnapshot:async()=>snapshot(),operationsDisplayForget:()=>new Promise(r=>finish=r)});try{await tick();const pending=f.ui.forget();assert.equal(f.w.localStorage.getItem('ks-operations-display-v1'),null);assert.match(f.root.textContent,/disconnected/);assert.equal(f.root.querySelectorAll('.tv-number').length,0);finish();await pending;}finally{f.close();}});
test('a generated code uses a separate key, registers only its hash and never changes the URL',async()=>{let registration;const f=fixture({operationsDisplayState:async()=>({ended:null}),operationsDisplayPair:async(code,hash)=>{registration={code,hash};return{ok:nano(Date.now()+600000)}}});try{await tick();f.root.querySelector('[data-new]').click();for(let i=0;i<8&&!registration;i++)await tick();await tick();const stored=JSON.parse(f.w.localStorage.getItem('ks-operations-display-v1'));assert.match(registration.code,/^[0-9a-f]{10}$/);assert.match(stored.secret,/^[0-9a-f]{64}$/);assert.notEqual(registration.hash,stored.secret);assert.equal(f.w.location.href,'https://hub.test/#/tv');assert.doesNotMatch(f.root.textContent,new RegExp(stored.secret));assert.match(f.root.textContent,/PAIR THIS SCREEN/);}finally{f.close();}});
test('manager requires an explicit source choice and safely handles expired pairing codes',async()=>{const dom=new JSDOM('<main></main>',{runScripts:'outside-only',url:'https://hub.test/#/screens'});const w=dom.window;w.eval(code);let saves=0;const ui=w.KebabDisplays.createManager(w.document.querySelector('main'),()=>({operationsDisplayAdmin:async()=>({canManage:true,displays:[]}),operationsSources:async()=>[{cid:1n,app:'assets'}],operationsDisplayApprove:async()=>{saves++;return{missing:null}}}));try{await ui.load();const form=w.document.querySelector('form');assert.equal(form.querySelectorAll(':checked').length,1,'only duration default, no source preselected');form.elements.code.value='ABCDE-12345';form.elements.screenName.value='IT room';form.dispatchEvent(new w.Event('submit',{cancelable:true}));await tick();assert.equal(saves,0);form.querySelector('[name=scope]').checked=true;form.dispatchEvent(new w.Event('submit',{cancelable:true}));await tick();assert.equal(saves,1);assert.match(form.textContent,/expired or was already used/);}finally{ui.stop();w.close();}});

test('an access confirmation older than 30 seconds clears even otherwise fresh metrics',async()=>{
 const start=Date.now();let current=start;
 const f=fixture({operationsDisplayState:async()=>ready(start),operationsDisplaySnapshot:async()=>snapshot(start)},{now:()=>current});
 try{await tick();await tick();assert.equal(f.root.querySelectorAll('.tv-number').length,1);current+=31000;await new Promise(r=>setTimeout(r,1100));assert.equal(f.root.querySelectorAll('.tv-number').length,0);assert.match(f.root.textContent,/Connection paused|expired/);}finally{f.close();}
});
