import {test} from 'node:test';import assert from 'node:assert/strict';import{readFileSync}from'node:fs';import{JSDOM}from'jsdom';
const flush=()=>new Promise(r=>setTimeout(r,0));
function setup(role='owner'){
 const dom=new JSDOM('<div id="updates"></div><div id="history"></div><div id="catalogue"></div>',{runScripts:'outside-only',url:'https://hub.test/#/apps/updates'}),w=dom.window;
 w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.dispatchEvent(new w.Event('close'));};
 w.eval(readFileSync(new URL('../dist/updates.js',import.meta.url),'utf8'));
 const recipes=[{id:'assets',name:'Assets',kind:'app',version:'2.0.0',runningVersion:'1.0.0',releaseId:'reviewed-release',installed:[{backend:'asset-id'}],state:'update_available',detail:'Update available',canUpdate:true,notes:'Release notes'},{id:'hub',name:'Hub',kind:'hub',version:'1.0.0',runningVersion:'1.0.0',releaseId:'hub-release',installed:[{}],state:'current',canUpdate:true}];
 const calls=[];let fail=false,resolveJob;
 const api={recipes:async()=>{if(fail)throw Error('Catalogue unavailable');return recipes;},checkForUpdates:async()=>api.recipes(),listJobs:async()=>[],info:async()=>({version:'0.7.0',me:'installer',pantryId:'source'}),applyRelease:async r=>{calls.push(r);return {ok:true,jobId:1n};},job:()=>new Promise(r=>resolveJob=r)};
 const roots=Object.fromEntries(['updates','history','catalogue'].map(id=>[id,w.document.getElementById(id)])),ui=w.KebabUpdates.create(roots,{role:()=>role,service:async()=>api});
 return {dom,w,ui,recipes,calls,roots,fail:()=>fail=true,finish:job=>resolveJob([job]),close:()=>{ui.dispose();dom.window.close();}};
}
test('owners review the exact release and repeated clicks cannot start another job',async()=>{const f=setup();try{const loading=f.ui.load();assert.match(f.roots.updates.textContent,/Loading software/);assert.doesNotMatch(f.roots.updates.textContent,/No applications/);await loading;f.roots.updates.querySelector('[data-u="review"]').click();assert.match(f.w.document.querySelector('dialog').textContent,/Release notes/);f.w.document.querySelector('[data-review-start]').click();await flush();assert.deepEqual(JSON.parse(JSON.stringify(f.calls)),[{id:'assets',releaseId:'reviewed-release',install:false}]);assert.equal(f.roots.updates.querySelector('[data-u="review"]'),null);assert.equal(f.roots.updates.querySelector('[data-u="reload"]').disabled,true);}finally{f.close();}});
test('failed catalogue checks cannot leave current badges or actionable stale releases',async()=>{const f=setup();try{await f.ui.load();assert.match(f.roots.updates.textContent,/verified current/);f.fail();await f.ui.load(true);assert.match(f.roots.updates.textContent,/Catalogue unavailable/);assert.equal(f.roots.updates.querySelector('[data-u="review"]'),null);assert.doesNotMatch(f.roots.updates.querySelector('[data-u="summary"]').textContent,/verified current/);assert.match(f.roots.updates.textContent,/Not checked/);}finally{f.close();}});
test('non-owners never fetch release administration',async()=>{const f=setup('admin');let called=false;try{await f.ui.load();assert.equal(f.ui.inventory().length,0);assert.equal(f.roots.updates.querySelector('button'),null);assert.match(f.roots.updates.textContent,/owners manage/);}finally{f.close();}});
test('newer installations and unavailable checks have no update action',async()=>{const f=setup();try{f.recipes[0].state='newer_installed';f.recipes[0].canUpdate=false;await f.ui.load();assert.match(f.roots.updates.textContent,/Newer version installed/);assert.equal(f.roots.updates.querySelector('[data-u="review"]'),null);}finally{f.close();}});
