import {test} from 'node:test';import assert from 'node:assert/strict';
import {domainState,domainCounts,groupEvents} from '../dist/workspace.js';import {canonicalDestination} from '../dist/canonical-url.js';
const now=Date.parse('2026-09-21T12:00:00Z'),at=BigInt(now)*1000000n;
const row={domain:{name:'example.test',types:['A'],enabled:true,lastCheck:at,lastResult:'ok'},records:[{rtype:'A',status:'ok',detail:''}],expiryDays:[],grade:'good',checks:[{certificateAt:at,postureAt:at,certificateDetail:'',certificateEnds:'2027-01-01',lookalikes:0n}]};
test('attention deduplicates findings and excludes paused domains',()=>{const warning={...row,grade:'weak',expiryDays:[2n],records:[{status:'changed',detail:''}]};assert.deepEqual(domainCounts([warning,{...warning,domain:{...warning.domain,enabled:false}}],{},now),{all:2,attention:1,expiring:1,paused:1});assert.equal(domainState(row,{},now).state,'ok');});
test('stale, pending and failed checks cannot appear healthy',()=>{for(const r of [{...row,domain:{...row.domain,lastCheck:at-4n*3600n*1000000000n}},{...row,checks:[{...row.checks[0],certificateDetail:'certificate check unavailable: upstream failed'}]},{...row,records:[{status:'ok',detail:'resolvers unreachable: network'}]}])assert.equal(domainState(r,{},now).state,'warn');assert.equal(domainState({...row,checks:[]},{},now).state,'pending');assert.equal(domainState({...row,records:[]},{},now).state,'pending');});
test('configured expiry threshold and delayed cadence are respected',()=>{assert.equal(domainState({...row,expiryDays:[40n]},{expiryWarnDays:45},now).expiring,true);assert.equal(domainState({...row,expiryDays:[40n]},{expiryWarnDays:30},now).expiring,false);assert.equal(domainState({...row,domain:{...row.domain,lastCheck:at-90n*60n*1000000000n}},{intervalMins:60},now).state,'ok');});
test('failure grouping preserves recovery boundaries',()=>{const e={domainId:1n,kind:'error',rtype:'cert',detail:'failed',at};const groups=groupEvents([{event:e},{event:e},{event:{...e,kind:'resolved'}},{event:e}]);assert.deepEqual(groups.map(g=>g.count),[2,1,1]);});
test('domain redirect carries public routes but never authentication fragments',()=>{const target='https://watch.example.com';assert.equal(canonicalDestination(target,'https://old.test/#/d/3'),target+'/#/d/3');assert.equal(canonicalDestination(target,'https://old.test/?token=secret#uht=secret'),target+'/');assert.equal(canonicalDestination(target,'https://old.test/#/d/3?token=secret'),target+'/');assert.equal(canonicalDestination('https://user:pass@watch.example.com','https://old.test/'),'');assert.equal(canonicalDestination('http://watch.example.com','https://old.test/'),'');assert.equal(canonicalDestination(target,target+'/#/overview'),'');});
