#!/usr/bin/env python3
"""Generate bounded, server-side civil-day data. Regenerate deliberately with tzdb updates.
Existing statement lines are immutable. Pending statements carry their own day boundaries.
Uses the same IANA catalogue as the planner. No network access required.
"""
import datetime as d, json, re, zoneinfo
from pathlib import Path
root=Path(__file__).resolve().parents[1]
zones=re.findall(r'"([^"]+)"',(root/'backend/oncall/Timezones.mo').read_text())
start=int(d.datetime(2020,1,1,tzinfo=d.timezone.utc).timestamp()); end=int(d.datetime(2041,1,1,tzinfo=d.timezone.utc).timestamp())
version='unknown local tzdb'
for tzroot in zoneinfo.TZPATH:
    metadata=Path(tzroot)/'tzdata.zi'
    if metadata.exists():
        version=metadata.read_text().splitlines()[0].removeprefix('# version '); break
groups=[]; names=[]
for name in zones:
    z=zoneinfo.ZoneInfo(name)
    def off(t): return int(d.datetime.fromtimestamp(t,z).utcoffset().total_seconds())
    points=[(start,off(start))]; t=start
    while t<end:
        nxt=min(t+86400,end); o=off(nxt)
        if o!=points[-1][1]:
            lo=t;hi=nxt
            while hi-lo>1:
                mid=(lo+hi)//2
                if off(mid)==points[-1][1]: lo=mid
                else: hi=mid
            points.append((hi,o))
        t=nxt
    if points not in groups: groups.append(points)
    names.append((name,groups.index(points)))
source='// Generated by desk/tools/generate-payroll-zones.py from IANA tzdb '+version+'.\n// UTC seconds, 2020-01-01 inclusive through 2041-01-01 exclusive.\nmodule {\n  public let start : Int = '+str(start)+';\n  public let end : Int = '+str(end)+';\n  public let names : [(Text, Nat)] = [\n'+',\n'.join('    ('+json.dumps(n)+', '+str(i)+')' for n,i in names)+'\n  ];\n  public let offsets : [[(Int, Int)]] = [\n'+',\n'.join('    ['+', '.join('(%d, %d)'%p for p in g)+']' for g in groups)+'\n  ];\n}\n'
(root/'backend/reporting/ZoneData.mo').write_text(source)
print(f'{len(names)} zones, {len(groups)} shared offset tables, {len(source)} bytes')
