import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import {renderIntakeReview} from '../dist/intake-review.js';
import {renderCommercialDetails} from '../dist/commercial-details.js';
const dom=new JSDOM('<main></main>');globalThis.document=dom.window.document;
const root=document.querySelector('main'),field=(field,newValue,basis='explicit')=>({field,newValue,basis,evidence:[{partId:'visual:doc:1',quote:'Read from original'}]});
const changes=[field('recordType','subscription'),field('title','Cloud subscription'),field('start','2026-03-13','ambiguous'),field('end','2027-03-12','ambiguous'),field('seats','150'),field('quantity','150'),field('unitMinor','480'),field('amountMinor','933984'),field('interval','year'),field('unitInterval','month'),field('renewalRule','auto'),field('noticeDays','30'),field('renewalTermMonths','12'),field('orderReference','Q-EXAMPLE'),field('purchaseOrder','PO-EXAMPLE'),field('paymentTerms','Net 30; Wire Transfer')];
let saved;
renderIntakeReview(root,{view:{source:{id:1n,subject:'Original order.pdf',fromName:'',fromAddr:'',contractId:[],note:''},proposals:[{id:2n,status:'open',contractId:[],kind:'subscription',summary:'Subscription',uncertainties:[],changes}],documents:[],text:''},spaces:[{id:'team:1',name:'IT',role:{owner:null},kind:'team',archived:false}],currentSpace:{id:'team:1',name:'IT'},canEdit:true,canTransfer:false,save:async data=>{saved=data;return {ok:true}},download:async()=>{},retry:async()=>{},remove:async()=>{},stale:()=>false});
assert.equal(document.querySelector('#review-start').value,'2026-03-13');assert.equal(document.querySelector('#review-end').value,'2027-03-12');assert.equal(document.querySelector('#review-unitMinor').value,'4.80');assert.equal(document.querySelector('#review-amountMinor').value,'9339.84');
assert.equal(document.querySelector('#review-unitInterval').value,'month');assert.equal(document.querySelector('#review-interval').value,'year');assert.match(document.querySelector('#review-start').closest('.review-field').textContent,/Check original/);
const type=document.querySelector('#review-recordType');type.value='receipt';type.dispatchEvent(new dom.window.Event('change'));type.value='subscription';type.dispatchEvent(new dom.window.Event('change'));
assert.equal(document.querySelectorAll('#review-unitInterval').length,1,'changing type does not duplicate or lose purchase fields');
await root.querySelector('form').onsubmit({preventDefault(){}});
const values=Object.fromEntries(saved.fields.map(f=>[f.field,f.value]));assert.equal(values.start,'2026-03-13');assert.equal(values.end,'2027-03-12');assert.equal(values.seats,'150');assert.equal(values.unitMinor,'480');assert.equal(values.amountMinor,'933984');assert.equal(values.purchaseOrder,'PO-EXAMPLE');assert.equal(values.unitInterval,'month');
let updates=0,finish;
renderCommercialDetails(root,{record:{canEdit:true,commercialDetails:[{field:'purchaseOrder',value:'PO-EXAMPLE'}]},save:()=>{updates++;return new Promise(r=>finish=r);},done:async()=>{},stale:()=>false});
root.querySelector('[data-edit-commercial]').click();const form=root.querySelector('form');form.elements.purchaseOrder.value='PO-EDITED';const a=form.onsubmit({preventDefault(){}});await form.onsubmit({preventDefault(){}});assert.equal(updates,1,'double save is prevented');finish({ok:false,detail:'Record changed'});await a;assert.match(root.textContent,/Record changed/);assert.equal(root.querySelector('[type=submit]').disabled,false);
console.log('Contracts review: dates, price periods, editable purchase fields and atomic save payload passed.');
