import {test} from 'node:test';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import {createAssignment} from '../dist/assignment.js';
const data={config:{revision:2n,defaultAssignee:'a',overrides:[{typeId:1n,assignee:'b'}]},people:[{id:'a',name:'Alex'},{id:'b',name:'Sam'}],requestTypes:[{id:1n,name:'Offboarding',enabled:true},{id:2n,name:'Other',enabled:true}],warnings:[]};
function fixture(extra={}){const dom=new JSDOM('<section id="root"></section>'),root=dom.window.document.querySelector('section');let me={role:'admin'};const api={getAutoAssignment:async()=>[data],...extra};const view=createAssignment({root,api:()=>api,session:{load:()=> 'token'},getMe:()=>me});return{dom,root,view,api,setMe:x=>{me=x;},close(){view.clear();dom.window.close();}};}
test('default and type exceptions save together; failed saves preserve choices',async()=>{let payload,calls=0,release;const f=fixture({saveAutoAssignment:async(_,x)=>{payload=x;calls++;return new Promise(r=>{release=r;});}});try{await f.view.show();const form=f.root.querySelector('form');assert.equal(form.elements.defaultOwner.value,'a');assert.equal(form.querySelector('[data-type="1"]').value,'b');assert.equal(form.querySelector('[data-type="2"]').value,'@default');form.elements.defaultOwner.value='b';form.querySelector('[data-type="1"]').value='';const saving=form.onsubmit({preventDefault(){}});await form.onsubmit({preventDefault(){}});assert.equal(calls,1);assert.equal(form.elements.defaultOwner.disabled,true);assert.deepEqual(payload,{revision:2n,defaultAssignee:'b',overrides:[{typeId:1n,assignee:''}]});release({ok:false,detail:'Assignment rules changed. Reload before saving.'});await saving;assert.equal(form.elements.defaultOwner.value,'b');assert.equal(form.elements.defaultOwner.disabled,false);assert.match(f.root.textContent,/Reload before saving/);}finally{f.close();}});
test('no empty owner is silently substituted for a revoked owner',async()=>{const f=fixture({getAutoAssignment:async()=>[{...data,config:{...data.config,defaultAssignee:'revoked'},warnings:['Default owner is unavailable.']}]});try{await f.view.show();const form=f.root.querySelector('form');assert.equal(form.elements.defaultOwner.value,'revoked');await form.onsubmit({preventDefault(){}});assert.match(f.root.textContent,/Replace unavailable owners/);}finally{f.close();}});
test('late settings responses cannot cross logout and nonadmins cannot load configuration',async()=>{let release,calls=0;const f=fixture({getAutoAssignment:()=>{calls++;return new Promise(r=>{release=r;});}});try{const request=f.view.show();f.setMe(null);f.view.clear();release([data]);await request;assert.equal(f.root.textContent,'');f.setMe({role:'agent'});await f.view.show();assert.equal(calls,1);}finally{f.close();}});
