import {test} from 'node:test';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import {createReporting,money} from '../dist/reporting.js';
import {calculationHTML} from '../dist/compensation.js';
const tick=()=>new Promise(r=>setImmediate(r));
function fixture(){const dom=new JSDOM('<main></main>',{url:'https://desk.test/#/reporting/policy-1',pretendToBeVisual:true});Object.assign(globalThis,{window:dom.window,document:dom.window.document,location:dom.window.location,FormData:dom.window.FormData});const root=document.querySelector('main');
 const policy={currency:'CHF',decimals:2n,readinessRates:[10000n,5000n],workRate:6000n,readinessCode:'READY',workCode:'WORK',costCenter:'OPS',retentionDays:90n};let calls=[];const api={reportingProjects:async()=>[{id:1n,name:'Operations',capabilities:{prepare:true},policy:[policy]}],reportingPeriods:async()=>[],reportingCompensationRules:async()=>[{revision:7n,rules:[]}],previewReportingCompensation:async(...args)=>{calls.push(args);return{ok:[{title:'Example <script>',seconds:1020n,payableSeconds:3600n,divisorSeconds:3600n,rate:60n,amount:60n,unit:{minutes:null}}]};},activateReportingCompensation:async(...args)=>{calls.push(args);return{ok:{id:1n,revision:8n}};}};const ui=createReporting({root,api:()=>api,session:{load:()=> 'session'},getMe:()=>({id:'hr',role:'requester',reporting:true})});return{dom,root,api,ui,calls,close:()=>{ui.clear();dom.window.close();}};}
function submit(c){const f=c.root.querySelector('#rpRules');f.requestSubmit(f.querySelector('button'));}
test('rules require server examples then explicit activation; exact values and revision are preserved',async()=>{const c=fixture();try{await c.ui.show('policy-1');assert.equal(c.root.querySelector('#rpActivate'),null);submit(c);await tick();assert.equal(c.calls.length,1);assert.equal(c.calls[0][2].policy.readinessRates[0],10000n);assert.equal(c.root.querySelector('script'),null);const form=c.root.querySelector('#rpActivate');assert.ok(form);form.querySelector('input').checked=true;form.requestSubmit(form.querySelector('button'));await tick();assert.equal(c.calls[1][2],7n);assert.deepEqual(c.calls[1][3],c.calls[0][2]);assert.equal(location.hash,'#/reporting/project-1');}finally{c.close();}});
test('editing rules invalidates both visible and in-flight previews',async()=>{const c=fixture();try{await c.ui.show('policy-1');submit(c);await tick();assert.ok(c.root.querySelector('#rpActivate'));const rate=c.root.querySelector('[name="work-weekday"]');rate.value='10';rate.dispatchEvent(new window.Event('input',{bubbles:true}));assert.equal(c.root.querySelector('#rpActivate'),null);let finish;c.api.previewReportingCompensation=()=>new Promise(r=>finish=r);submit(c);await tick();rate.value='20';rate.dispatchEvent(new window.Event('input',{bubbles:true}));finish({ok:[]});await tick();assert.equal(c.root.querySelector('#rpActivate'),null);assert.match(c.root.textContent,/changed while calculating/);}finally{c.close();}});
test('late preview cannot restore financial data after clearing the session',async()=>{const c=fixture();try{await c.ui.show('policy-1');let finish;c.api.previewReportingCompensation=()=>new Promise(r=>finish=r);submit(c);await tick();c.ui.clear();finish({ok:[]});await tick();assert.equal(c.root.textContent,'');}finally{c.close();}});
test('calculation keeps credit minutes separate from money and escapes names',()=>{const common={name:'<img src=x>',code:'TIME',date:'2026-10-25',dayKind:{holiday:null},basis:{hour:null},seconds:1020n,payableSeconds:3600n,divisorSeconds:3600n,rate:90n,amount:90n,ruleRevision:1n,recordIds:[1n,2n],decimals:0n,currency:''};const html=calculationHTML({rule:[],lines:[{...common,unit:{minutes:null}}]},money);assert.match(html,/Time credit/);assert.match(html,/90 min/);assert.ok(!html.includes('<img'));assert.match(html,/1, 2/);});
