import {renderServiceStatus} from '../dist/service-status.js';
import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {JSDOM} from 'jsdom';
import {createCustomerProjects} from '../dist/customer-projects.js';
const tick=()=>new Promise(r=>setTimeout(r,15));
const p={id:1n,revision:1n,name:'Orbit <script>bad()</script>',description:'Product support',group:'Product team',enabled:true,widgetEnabled:true,widgetId:'ab'.repeat(32),fields:[],origins:['https://product.test']};
function context(role='admin') {const dom=new JSDOM('<div id="root"></div>',{url:'https://desk.test/#/customers',pretendToBeVisual:true});globalThis.window=dom.window;globalThis.document=dom.window.document;globalThis.location=dom.window.location;let me={id:'a',role};const api={customerWorkflowTeams:async()=>[],listCustomerProjects:async()=>[p],customerProjectKeys:async()=>[],customerProjectTickets:async()=>[],createCustomerKey:async()=>({ok:true,secret:'SECRET_ONLY_ONCE',detail:''})};const root=document.getElementById('root');const ui=createCustomerProjects({root,api:()=>api,session:{load:()=> 'staff-session'},getMe:()=>me,backendId:'placeholder'});return{dom,root,ui,api,setMe:m=>me=m};}

test('projects show scoped workspaces, escape content and hide settings from agents',async()=>{const{root,ui}=context('agent');await ui.show();assert.match(root.textContent,/Orbit <script>/);assert.equal(root.querySelector('script'),null);assert.equal(root.querySelector('[href="#/customers/new"]'),null);await ui.show('1','settings');assert.equal(root.querySelector('#customerProjectForm'),null);assert.ok(root.querySelector('#customerRows'));assert.match(root.textContent,/No requests/);});
test('one-time API secret disappears on navigation and sign-out; late responses cannot restore it',async()=>{const{root,ui,api}=context();await ui.show('1','settings');await tick();root.querySelector('#cpKeyName').value='Product backend';root.querySelector('#cpCreateKey').click();await tick();assert.equal(root.querySelector('#cpNewSecret').value,'SECRET_ONLY_ONCE');ui.clear();assert.equal(root.textContent,'');await ui.show('1','settings');let resolve;api.createCustomerKey=()=>new Promise(r=>resolve=r);root.querySelector('#cpKeyName').value='Slow';root.querySelector('#cpCreateKey').click();ui.clear();resolve({ok:true,secret:'LATE_SECRET'});await tick();assert.equal(root.textContent,'');});
test('project selection races cannot render a stale workspace after leaving',async()=>{const{root,ui,api}=context();let resolve;api.listCustomerProjects=()=>new Promise(r=>resolve=r);const pending=ui.show('1');ui.clear();resolve([p]);await pending;assert.equal(root.textContent,'');});

function publicPage(hash,fetch) {const dom=new JSDOM('<main id="support"></main>',{url:'https://desk.test/support.html#'+hash,runScripts:'outside-only',pretendToBeVisual:true});dom.window.renderServiceStatus=renderServiceStatus;dom.window.fetch=fetch;dom.window.AbortController=AbortController;dom.window.setInterval=()=>0;let script=fs.readFileSync(new URL('../dist/support.js',import.meta.url),'utf8').replace(/^import[^\n]+\n/gm,'');script="const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',\"'\":'&#39;'}[c]));\n"+script;dom.window.eval(script);return dom;}
const response=(body,status=200)=>({ok:status<300,status,json:async()=>body});
test('public form retries the exact token and body after a lost response without Hub login',async()=>{const requests=[],dom=publicPage('form/'+'ab'.repeat(32),async(url,args)=>{requests.push({url,args});if(url.endsWith('/schema'))return response({...p,id:1,revision:1,name:'Orbit',fields:[]});if(requests.length===2)throw new Error('Connection lost');return response({id:42,key:'SUP-42',url:'https://desk.test/support.html#ticket/42/'+JSON.parse(args.body).clientToken});});await tick();const d=dom.window.document;for(const[id,value]of Object.entries({name:'Customer',email:'customer@test.example',subject:'Help',body:'Original message'}))d.getElementById(id).value=value;const form=d.getElementById('requestForm');form.dispatchEvent(new dom.window.Event('submit',{cancelable:true}));await tick();assert.equal(d.getElementById('body').disabled,true);form.dispatchEvent(new dom.window.Event('submit',{cancelable:true}));await tick();assert.equal(requests[1].args.body,requests[2].args.body);assert.match(d.body.textContent,/Save your private ticket link/);assert.match(JSON.parse(requests[1].args.body).clientToken,/^[a-f0-9]{64}$/);assert.ok(requests.every(r=>!r.url.includes('hub')&&r.args.credentials==='omit'));assert.equal(requests[1].args.headers.Authorization,undefined);dom.window.close();});
test('customer conversation renders untrusted content as text and sends the private capability only in a header',async()=>{const requests=[],secret='cd'.repeat(32),dom=publicPage('ticket/42/'+secret,async(url,args)=>{requests.push({url,args});return response({key:'SUP-42',project:'Orbit',subject:'<img src=x onerror=bad()>',body:'Customer content',status:'open',fields:{order_id:'<script>bad()</script>'},linkExpiresAt:String(Date.now()+86400000),comments:[{author:'Support team',body:'<script>bad()</script>',at:String(Date.now())}]});});await tick();assert.equal(dom.window.document.querySelector('img,script'),null);assert.match(dom.window.document.body.textContent,/<script>/);assert.ok(requests.every(r=>!r.url.includes(secret)&&r.args.headers.Authorization==='Bearer '+secret));dom.window.close();});

test('project settings expose embedding guidance and require a deliberate confirmation for shorter retention',async()=>{
 const{root,ui,api}=context();let policy={revision:0n,completedDays:90n,inactiveDays:365n,noticeUrl:'',graceUntil:0n},saved=[];
 api.customerPrivacy=async()=>[{policy:{...policy},tickets:4n,due:0n,held:0n,nextDeletion:0n,lastSweep:0n,journalEntries:0n}];
 api.saveCustomerPrivacy=async(...args)=>{saved.push(args);policy={...policy,...args[3],revision:1n};return{ok:true,detail:'Saved retention'};};
 await ui.show('1','settings');await tick();assert.ok(root.querySelector('.page-heading a[href="./customer-support.html"]'));assert.match(root.textContent,/Embedding guide/);assert.match(root.textContent,/Automatic deletion on/);
 const field=root.querySelector('#cpCompletedDays');field.value='7';field.dispatchEvent(new window.Event('input',{bubbles:true}));assert.equal(root.querySelector('#cpShorter').classList.contains('hidden'),false);
 const form=root.querySelector('#cpPrivacyForm'),button=form.querySelector('button[type=submit]');form.dispatchEvent(new window.SubmitEvent('submit',{cancelable:true,submitter:button}));await tick();assert.equal(saved.length,0);
 root.querySelector('#cpConfirmShorter').checked=true;form.dispatchEvent(new window.SubmitEvent('submit',{cancelable:true,submitter:button}));await tick();assert.equal(saved.length,1);assert.equal(saved[0][3].completedDays,7n);assert.equal(saved[0][4],true);assert.match(root.textContent,/Saved retention/);
});

test('late privacy response cannot rebuild settings after navigation or loss of admin',async()=>{
 const{root,ui,api,setMe}=context();let resolve;api.customerPrivacy=()=>new Promise(r=>resolve=r);await ui.show('1','settings');ui.clear();resolve([{policy:{revision:0n,completedDays:90n,inactiveDays:365n,noticeUrl:'',graceUntil:0n}}]);await tick();assert.equal(root.textContent,'');
 await ui.show('1','settings');setMe({id:'a',role:'agent'});resolve([{policy:{revision:0n,completedDays:90n,inactiveDays:365n,noticeUrl:'',graceUntil:0n}}]);await tick();assert.equal(root.querySelector('#cpPrivacyForm'),null);
});

test('private portal removes loaded personal content and the capability when deletion or expiry is detected',async()=>{
 let gone=false;const dom=publicPage('ticket/42/'+'cd'.repeat(32),async()=>gone?response({error:'Ticket unavailable'},404):response({key:'SUP-42',project:'Orbit',subject:'Private subject',body:'PERSONAL MESSAGE',status:'open',fields:{order_id:'PRIVATE ORDER'},linkExpiresAt:String(Date.now()+86400000),deleteAt:String(Date.now()+86400000),privacy:{completedDays:7,inactiveDays:30,noticeUrl:'https://company.test/privacy'},comments:[]}));await tick();
 const d=dom.window.document;assert.match(d.body.textContent,/Scheduled deletion/);assert.equal(d.querySelector('a').href,'https://company.test/privacy');d.getElementById('reply').value='PRIVATE UNSENT DRAFT';gone=true;d.getElementById('refresh').click();await tick();assert.match(d.body.textContent,/no longer available/);assert.ok(!d.body.textContent.includes('PERSONAL MESSAGE'));assert.equal(d.querySelector('textarea'),null);assert.equal(dom.window.location.hash,'');dom.window.close();
});

test('workflow editor saves a project-local refund template, ordered steps and typed fields',async()=>{
 const{root,ui,api}=context();let saved;api.listCustomerTypes=async()=>[];api.saveCustomerType=async(...args)=>{saved=args;return{ok:true,id:9n};};
 await ui.show('1','types');root.querySelector('#cwRefund').click();assert.equal(root.querySelector('#cwName').value,'Refund request');assert.equal(root.querySelectorAll('[data-step]').length,3);assert.equal(root.querySelector('#cwfk0').value,'order_id');
 const group=root.querySelector('#cwsg1');group.value='Finance';group.dispatchEvent(new window.Event('input',{bubbles:true}));root.querySelector('[data-move="2"][data-dir="-1"]').click();assert.equal(root.querySelector('#cwsn1').value,'Refund confirmation');
 const form=root.querySelector('#cwForm');form.dispatchEvent(new window.SubmitEvent('submit',{cancelable:true,submitter:form.querySelector('[type=submit]')}));await tick();assert.equal(saved[1],p.id);assert.equal(saved[2],p.revision);assert.equal(saved[4].fields[0].required,true);assert.equal(saved[4].steps[2].approval,true);assert.equal(saved[4].steps[2].group,'Finance');assert.match(root.textContent,/A useful starting point/);
});

test('workflow configuration discards late responses after sign-out and hides the editor from agents',async()=>{
 const{root,ui,api,setMe}=context();let resolve;api.listCustomerTypes=()=>new Promise(r=>resolve=r);const pending=ui.show('1','types');await tick();ui.clear();resolve([]);await pending;assert.equal(root.textContent,'');
 setMe({id:'a',role:'agent'});await ui.show('1','types');assert.equal(root.querySelector('#cwNew'),null);assert.ok(root.querySelector('#customerRows'));
});

test('public type selection uses only its fields and preserves the chosen type on uncertain retries',async()=>{
 let calls=[];const dom=publicPage('form/'+'ab'.repeat(32)+'/8',async(url,args)=>{if(url.endsWith('/schema'))return response({name:'Orbit',revision:4,defaultTypeId:7,fields:[],requestTypes:[{id:7,name:'General',description:'Questions',fields:[]},{id:8,name:'Refund',description:'Review a purchase',fields:[{key:'order_id',title:'Order',kind:'text',required:true,options:[]}]}]});calls.push(JSON.parse(args.body));throw Error('Response lost');});await tick();const d=dom.window.document;assert.equal(d.getElementById('requestType').value,'8');for(const[id,value]of Object.entries({name:'Customer',email:'customer@test.example',subject:'Refund',body:'Please review','field-order_id':'O-123'}))d.getElementById(id).value=value;
 const form=d.getElementById('requestForm');form.dispatchEvent(new dom.window.Event('submit',{cancelable:true}));await tick();assert.equal(d.getElementById('requestType').disabled,true);form.dispatchEvent(new dom.window.Event('submit',{cancelable:true}));await tick();assert.deepEqual(calls[1],calls[0]);assert.equal(calls[0].typeId,8);assert.deepEqual(calls[0].fields,{order_id:'O-123'});dom.window.close();
});
