import {test} from 'node:test';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import {createOncallAlerts,connectionCommands,sourceStatus} from '../dist/oncall-alerts.js';
const flush=()=>new Promise(r=>setImmediate(r));
function fixture(role='admin'){
 const dom=new JSDOM('<main id="root"></main>',{url:'https://desk.test/#/oncall/1/sources',pretendToBeVisual:true});Object.assign(globalThis,{window:dom.window,document:dom.window.document,location:dom.window.location});
 let me={id:'a',role};const root=document.getElementById('root'),w={project:{id:1n,name:'Operations',services:['API']}};
 const s={id:1n,projectId:1n,name:'Checks <img src=x>',service:'API',revision:1n,createdAt:1n,enabled:false,revokedAt:0n,expiresAt:BigInt(Date.now()+86400000)*1000000n,previousUntil:0n,testedAt:0n,receivedAt:0n,accepted:0n,rejected:0n,lastError:''};
 const api={oncallAlertSources:async()=>[[s]]},ui=createOncallAlerts({root,api:()=>api,session:{load:()=> 'token'},getMe:()=>me,endpoint:'https://backend.test'});
 return{root,w,s,api,ui,setMe:x=>{me=x;},close:()=>{ui.clear();dom.window.close();}};
}
test('source guide distinguishes safe testing from real response and escapes names',async()=>{const c=fixture();try{await c.ui.show(c.w,'source-1');assert.equal(c.root.querySelector('img'),null);assert.match(c.root.textContent,/Checks <img/);assert.equal(c.root.querySelector('[data-source-action]').disabled,true);assert.match(c.root.textContent,/starts real response/);assert.match(c.root.querySelector('[data-code="test"]').textContent,/sources\/1\/test/);assert.ok(!c.root.querySelector('input[type=password]'));c.s.testedAt=1n;await c.ui.show(c.w,'source-1');assert.equal(c.root.querySelector('[data-source-action]').disabled,false);}finally{c.close();}});
test('key appears once after creation and is removed when navigating away',async()=>{const c=fixture();try{const value='a'.repeat(64);c.api.createOncallAlertSource=async()=>({ok:{id:1n,revision:1n,secret:value}});await c.ui.show(c.w,'source-new');c.root.querySelector('#sName').value='Source';c.root.querySelector('button[type=submit]').click();await flush();await flush();assert.equal(c.root.querySelector('#sourceSecret').value,value);assert.equal(window.localStorage.length,0);assert.ok(!location.href.includes(value));assert.match(location.hash,/source-1/);c.ui.clear();assert.equal(c.root.querySelector('#sourceSecret'),null);}finally{c.close();}});
test('late creation result cannot reveal a secret after account or route changes',async()=>{const c=fixture();try{let finish;c.api.createOncallAlertSource=()=>new Promise(r=>finish=r);await c.ui.show(c.w,'source-new');c.root.querySelector('#sName').value='Source';c.root.querySelector('button[type=submit]').click();c.ui.clear();c.root.replaceChildren();c.setMe({id:'b',role:'agent'});finish({ok:{id:1n,revision:1n,secret:'b'.repeat(64)}});await flush();assert.equal(c.root.querySelector('#sourceSecret'),null);assert.equal(c.root.textContent,'');}finally{c.close();}});
test('source polling clears credentials and details on access loss',async(t)=>{const c=fixture();t.mock.timers.enable({apis:['setTimeout']});try{await c.ui.show(c.w,'source-1');c.api.oncallAlertSources=async()=>[];t.mock.timers.tick(10000);await flush();assert.equal(c.root.querySelector('#sEndpoint'),null);assert.match(c.root.textContent,/access changed/);}finally{c.close();t.mock.timers.reset();}});
test('revoke is explicit and API failure keeps the source visible',async()=>{const c=fixture();try{let calls=0;c.api.setOncallAlertSource=async()=>{calls++;return{err:{stale:null}};};await c.ui.show(c.w,'source-1');c.root.querySelector('[data-revoke]').click();assert.equal(calls,0);assert.match(c.root.textContent,/permanently rejects both keys/);c.root.querySelector('[data-confirm]').click();await flush();assert.equal(calls,1);assert.match(c.root.textContent,/changed/);assert.ok(c.root.querySelector('#sEndpoint'));}finally{c.close();}});
test('expired or revoked keys never look active and examples do not embed secrets',()=>{assert.equal(sourceStatus({enabled:true,expiresAt:1n}),'Key expired');assert.equal(sourceStatus({enabled:true,revokedAt:1n,expiresAt:1n}),'Revoked');const c=connectionCommands('https://backend.test/oncall/v1/sources/1');assert.match(c.test,/read -r -s DESK_ALERT_KEY/);assert.match(c.event,/"sequence": "1"/);assert.match(c.event,/persist|Persist/);});
