import {test} from 'node:test';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import {createOncallResponse} from '../dist/oncall-response.js';
const flush=()=>new Promise(r=>setImmediate(r));
function fixture(role='admin'){
 const dom=new JSDOM('<main id="root"></main>',{url:'https://desk.test/#/oncall/1/incidents',pretendToBeVisual:true});Object.assign(globalThis,{window:dom.window,document:dom.window.document,location:dom.window.location});
 let me={id:'a',role};const at=BigInt(Date.now()-600000)*1000000n;
 const w={project:{id:1n,name:'Operations',services:['API']},members:[{id:'a',name:'Alex'},{id:'b',name:'Blair'}],plans:[],canManage:role==='admin'},i={id:1n,projectId:1n,title:'Unsafe <img src=x>',service:'API',severity:{major:null},status:{open:null},owner:'',ownerName:'',openedAt:at,updatedAt:at,revision:1n,nextEscalation:at+3600000000000n,routeIssue:'',resolution:''};
 const o={policy:[{revision:1n,enabled:true,ackMinutes:5n,fallback:'a',retentionDays:90n}],incidents:[i],canManage:role==='admin',deliveryReady:true},v={incident:i,events:[{name:'Blair',kind:'note',at,text:'<script>bad()</script>'}],deliveries:[],work:[],handoff:[]};
 const api={oncallResponse:async()=>[o],oncallIncident:async()=>[v]},root=document.getElementById('root'),ui=createOncallResponse({root,api:()=>api,session:{load:()=> 'token'},getMe:()=>me});
 return{root,ui,w,o,v,api,setMe:m=>{me=m;},cleanup:()=>{ui.clear();dom.window.close();}};
}
test('incident text is escaped and acknowledgement does not invent a work record',async()=>{const c=fixture();try{let calls=0;c.api.acknowledgeOncallIncident=async()=>{calls++;return{err:{stale:null}};};c.api.recordOncallWork=async()=>{throw Error('must not record time on acknowledgement');};await c.ui.show(c.w,'incident-1');assert.equal(c.root.querySelector('img,script'),null);assert.match(c.root.textContent,/<script>bad/);c.root.querySelector('#rAck').click();await flush();assert.equal(calls,1);assert.match(c.root.textContent,/record changed/);}finally{c.cleanup();}});
test('handoff acceptance belongs to the recipient, not the project administrator',async()=>{const c=fixture();try{Object.assign(c.v.incident,{status:{acknowledged:null},owner:'a',ownerName:'Alex'});c.v.handoff=[{from:'a',to:'b',toName:'Blair',summary:'Keep <private> context',status:{pending:null}}];await c.ui.show(c.w,'incident-1');assert.equal(c.root.querySelector('[data-handoff="accept"]'),null);assert.ok(c.root.querySelector('[data-handoff="cancel"]'));c.setMe({id:'b',role:'agent'});await c.ui.show(c.w,'incident-1');assert.ok(c.root.querySelector('[data-handoff="accept"]'));assert.match(c.root.textContent,/Alex remains responsible/);}finally{c.cleanup();}});
test('response access loss clears an in-progress note instead of retaining privileged data',async(t)=>{const c=fixture();t.mock.timers.enable({apis:['setTimeout']});try{await c.ui.show(c.w,'incident-1');const note=c.root.querySelector('#rNote');note.value='Private draft';note.dispatchEvent(new window.Event('input',{bubbles:true}));c.api.oncallIncident=async()=>[];t.mock.timers.tick(10000);await flush();assert.equal(c.root.querySelector('#rNote'),null);assert.match(c.root.textContent,/access changed|record expired/);}finally{c.cleanup();t.mock.timers.reset();}});
test('response view cannot reappear after account switching or navigation',async()=>{const c=fixture();try{let finish;c.api.oncallResponse=()=>new Promise(r=>finish=r);const pending=c.ui.show(c.w,'incidents');c.setMe({id:'b',role:'admin'});finish([c.o]);await pending;assert.equal(c.root.textContent,'');}finally{c.cleanup();}});

test('refresh preserves unsent input within an incident but never across incidents',async()=>{const c=fixture();try{await c.ui.show(c.w,'incident-1');const input=c.root.querySelector('#rNote');input.value='Keep my investigation';input.dispatchEvent(new window.Event('input',{bubbles:true}));await c.ui.show(c.w,'incident-1');assert.equal(c.root.querySelector('#rNote').value,'Keep my investigation');c.v.incident.id=2n;await c.ui.show(c.w,'incident-2');assert.equal(c.root.querySelector('#rNote').value,'');}finally{c.cleanup();}});

test('monitoring recovery remains distinct from response ownership in the incident view',async()=>{const c=fixture();try{c.v.monitoring=[{sourceName:'Health checks <private>',condition:'recovered',occurredAt:c.v.incident.openedAt,receivedAt:c.v.incident.openedAt}];await c.ui.show(c.w,'incident-1');assert.match(c.root.textContent,/Recovery reported/);assert.match(c.root.textContent,/Ownership and escalation continue/);assert.ok(c.root.querySelector('#rAck'),'a monitoring recovery does not remove human acknowledgement');assert.equal(c.root.querySelector('private'),null);}finally{c.cleanup();}});
