import {test} from 'node:test';import assert from 'node:assert/strict';import {JSDOM} from 'jsdom';import {createQueueBulk} from '../dist/queue-bulk.js';
const tick=()=>new Promise(r=>setTimeout(r,20));
function setup(count=3){
 const dom=new JSDOM('<div id="root"></div><input id="all" type="checkbox"><table><tbody></tbody></table>',{url:'https://desk.test',pretendToBeVisual:true}),d=dom.window.document;
 const rows=Array.from({length:count},(_,i)=>({id:BigInt(i+1),updatedAt:10n,key:'IT-'+(i+1)})),table=d.querySelector('tbody'),root=d.querySelector('#root'),selectAll=d.querySelector('#all');
 table.innerHTML=rows.map(r=>`<tr><td><input type="checkbox" data-select-ticket="${r.id}"></td></tr>`).join('');
 let who={id:'agent',role:'agent'},calls=[],pages=0;
 const api={bulkInternalTickets:async(_,items,action)=>{calls.push({items,action});return{ok:items.map(r=>({id:r.id,result:{updated:null}}))};},internalQueuePage:async()=>{pages++;return[{rows:[{id:99n,updatedAt:4n,key:'IT-99'}],total:BigInt(count+1),next:[]}];}};
 const ui=createQueueBulk({root,table,selectAll,api:()=>api,session:{load:()=> 'token'},getMe:()=>who,loadAgents:async()=>[{id:'other',displayName:'Other <Agent>'}],refresh:async()=>ui.setRows(rows,{total:BigInt(count),next:[]},{}),freeze:()=>{}});
 ui.setRows(rows,{total:BigInt(count),next:[]},{});
 return{dom,d,rows,root,table,selectAll,ui,api,calls,changeWho:v=>who=v,pages:()=>pages};
}
const choose=(x,value)=>{const el=x.d.querySelector('#bulk-action');el.value=value;el.dispatchEvent(new x.dom.window.Event('change'));};
const submit=x=>x.root.querySelector('form').dispatchEvent(new x.dom.window.Event('submit',{cancelable:true}));
test('selection is explicit, indeterminate and clearable; assign-to-me never fires before Apply',async()=>{const x=setup();x.table.querySelector('input').click();assert.equal(x.selectAll.indeterminate,true);assert.equal(x.calls.length,0);submit(x);await tick();assert.equal(x.calls.length,1);assert.equal(x.calls[0].action.assign,'agent');assert.equal(x.calls[0].items.length,1);assert.match(x.root.textContent,/1 updated/);assert.equal(x.root.querySelector('form'),null);});
test('all matching selection fetches further pages; large writes are bounded and cannot double-submit',async()=>{const x=setup(101);x.ui.setRows(x.rows,{total:102n,next:[1n]},{});x.selectAll.click();x.root.querySelector('[data-all]').click();await tick();assert.equal(x.pages(),1);assert.match(x.root.textContent,/101 selected/); // Returned fixture id 99 already exists; no duplicate.
 submit(x);submit(x);await tick();assert.equal(x.calls.length,3);assert.deepEqual(x.calls.map(c=>c.items.length),[50,50,1]);});
test('owner, waiting reason, UTC date and clearing are explicit payloads',async()=>{for(const [action,expected]of [['assign',{assign:'other'}],['unassign',{assign:''}],['status',{status:{status:'waiting',waitingOn:'third-party'}}],['due',{due:[1791158400000000000n]}],['clearDue',{due:[]}]]){const x=setup();x.selectAll.click();choose(x,action);await tick();if(action==='assign')x.d.querySelector('#bulk-owner').value='other';if(action==='status')x.d.querySelector('#bulk-state').value='waiting:third-party';if(action==='due')x.d.querySelector('#bulk-date').value='2026-10-05';submit(x);await tick();assert.deepEqual(x.calls[0].action,expected);}});
test('partial and uncertain results are visible without rerunning completed requests',async()=>{const x=setup();x.api.bulkInternalTickets=async()=>({ok:[{id:1n,result:{updated:null}},{id:2n,result:{unchanged:null}},{id:3n,result:{skipped:'Checklist <script> is open'}}]});x.selectAll.click();submit(x);await tick();assert.match(x.root.textContent,/1 updated · 1 already matched · 1 need review/);assert.equal(x.root.querySelector('script'),null);assert.match(x.root.querySelector('details').textContent,/IT-3/);
 x.selectAll.click();x.api.bulkInternalTickets=async()=>{throw Error('network');};submit(x);await tick();assert.match(x.root.textContent,/3 need review/);assert.match(x.root.textContent,/not confirmed/);});
test('navigation/sign-out stops later batches and rejects late selection results',async()=>{const x=setup(60);let resolve; x.api.bulkInternalTickets=()=>new Promise(r=>resolve=r);x.selectAll.click();submit(x);x.ui.clear();resolve({ok:[]});await tick();assert.equal(x.root.textContent,'');assert.equal(x.ui.busy,false);
 const y=setup();let done;y.api.internalQueuePage=()=>new Promise(r=>done=r);y.ui.setRows(y.rows,{total:4n,next:[1n]},{});y.selectAll.click();y.root.querySelector('[data-all]').click();y.ui.clear();y.changeWho({id:'employee',role:'requester'});done([{rows:[],total:4n,next:[]}]);await tick();assert.equal(y.root.textContent,'');});

test('changing selection preserves the chosen action and date; queue loading disables writes',async()=>{const x=setup();x.table.querySelector('input').click();choose(x,'due');x.d.querySelector('#bulk-date').value='2026-10-05';x.table.querySelectorAll('input')[1].click();assert.equal(x.d.querySelector('#bulk-action').value,'due');assert.equal(x.d.querySelector('#bulk-date').value,'2026-10-05');x.ui.loading(true);submit(x);assert.equal(x.calls.length,0);assert.equal(x.selectAll.disabled,true);x.ui.loading(false);assert.equal(x.d.querySelector('#bulk-date').value,'2026-10-05');submit(x);await tick();assert.equal(x.calls[0].items.length,2);assert.ok('due'in x.calls[0].action);});

test('a denied batch has a clear access error and does not submit later batches',async()=>{const x=setup(60);let calls=0;x.api.bulkInternalTickets=async()=>{calls++;return{denied:null};};x.selectAll.click();submit(x);await tick();assert.equal(calls,1);assert.match(x.root.textContent,/60 need review/);assert.match(x.root.textContent,/Desk access is unavailable/);assert.doesNotMatch(x.root.textContent,/Result not confirmed/);});
