import {test} from 'node:test';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import {createReporting,parseMoney,money} from '../dist/reporting.js';
const tick=()=>new Promise(r=>setImmediate(r));
function fixture(){const dom=new JSDOM('<main></main>',{url:'https://desk.test/#/reporting/1',pretendToBeVisual:true});Object.assign(globalThis,{window:dom.window,document:dom.window.document,location:dom.window.location,FormData:dom.window.FormData});const root=document.querySelector('main');let me={id:'me',role:'requester',reporting:true};const start=BigInt(Date.now()-86400000)*1000000n;
 const caps={prepare:false,review:true,release:false,export:false},p={id:1n,projectId:1n,title:'September <img src=x>',startAt:start,endAt:start+1000000000n,timezone:'UTC',revision:1n,createdBy:'hr',approvedAt:0n,approvedBy:'',batchId:'',adjustmentOf:0n,coverageIssues:0n,coverageNote:'',sourceChanged:false,deleteAt:start+90n*86400000000000n};
 const record={id:1n,personId:'other',name:'Alex',kind:{readiness:null},layer:0n,startAt:start,endAt:start+1000000000n,breakMinutes:0n,note:'',delta:0n,state:{confirmed:null},reason:'',confirmedBy:'other'};
 const v={period:p,capabilities:caps,policy:[],records:[record],lines:[],mappings:[],departed:[],adjustmentPeople:[],audit:[],blockers:[]};const api={reportingProjects:async()=>[{id:1n,name:'Operations',capabilities:caps,policy:[]}],reportingPeriods:async()=>[p],reportingPeriod:async()=>[structuredClone(v)]};const ui=createReporting({root,api:()=>api,session:{load:()=> 'session'},getMe:()=>me});return{root,ui,api,v,setMe:x=>me=x,close:()=>{ui.clear();dom.window.close();}};}
test('money parsing and display avoid floating-point cents and reject silent rounding',()=>{assert.equal(parseMoney('19.99',2),1999n);assert.equal(parseMoney('-0.05',2),-5n);assert.equal(money(-5n,2),'-0.05');assert.equal(money(25n,0),'25');assert.throws(()=>parseMoney('1.001',2));assert.throws(()=>parseMoney('1e2',2));assert.throws(()=>parseMoney('1.1',0));});
test('review-only UI omits financial setup, export and incident navigation; user content is escaped',async()=>{const c=fixture();try{await c.ui.show('1');assert.match(c.root.textContent,/September <img/);assert.equal(c.root.querySelector('img'),null);assert.equal(c.root.querySelector('[data-export]'),null);assert.equal(c.root.querySelector('[data-release]'),null);assert.ok(c.root.querySelector('[data-action="approve"]'));assert.equal(c.root.querySelector('[data-action="confirm"]'),null);assert.equal(c.root.querySelector('a[href*="incident"]'),null);}finally{c.close();}});
test('review decision sends exact period revision and keeps stale edits visible',async()=>{const c=fixture();try{let args;c.api.reviewReportingRecord=async(...a)=>{args=a;return{err:{stale:null}};};await c.ui.show('1');c.root.querySelector('[data-action="approve"]').click();c.root.querySelector('#rpDecision').requestSubmit(c.root.querySelector('#rpDecision button'));await tick();assert.equal(args[1],1n);assert.equal(args[3],1n);assert.match(c.root.textContent,/changed/);}finally{c.close();}});
test('access loss removes financial data even while a form is open',async(t)=>{const c=fixture();t.mock.timers.enable({apis:['setTimeout']});try{await c.ui.show('1');c.root.querySelector('[data-action="approve"]').click();c.api.reportingPeriod=async()=>[];t.mock.timers.tick(30000);await tick();assert.equal(c.root.querySelector('table'),null);assert.equal(c.root.querySelector('#rpDecision'),null);assert.match(c.root.textContent,/Access expired/);}finally{c.close();t.mock.timers.reset();}});
test('late responses cannot restore a cleared reporting session',async()=>{const c=fixture();try{let finish;c.api.reportingPeriod=()=>new Promise(r=>finish=r);const loading=c.ui.show('1');await tick();c.ui.clear();finish([c.v]);await loading;assert.equal(c.root.textContent,'');}finally{c.close();}});
test('participant sees own confirmation instead of reviewer approval',async()=>{const c=fixture();try{c.v.capabilities.review=false;c.v.records[0].personId='me';c.v.records[0].confirmedBy='';c.v.records[0].state={pending:null};await c.ui.show('1');assert.ok(c.root.querySelector('[data-action="confirm"]'));assert.equal(c.root.querySelector('[data-action="approve"]'),null);}finally{c.close();}});
test('Finance gets no empty review column and zero-attention filters explain the empty view',async()=>{const c=fixture();try{c.v.capabilities.review=false;c.v.capabilities.release=true;c.v.capabilities.export=true;c.v.records[0].state={approved:null};await c.ui.show('1');assert.equal([...c.root.querySelectorAll('th')].some(x=>x.textContent==='Review'),false);c.root.querySelector('[data-filter="attention"]').click();assert.equal(c.root.querySelector('[data-record-empty]').hidden,false);c.root.querySelector('[data-filter="all"]').click();assert.equal(c.root.querySelector('[data-record-empty]').hidden,true);}finally{c.close();}});
