import {test} from 'node:test';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import {createWorkboard,workLink} from '../dist/workboard.js';
const now=BigInt(Date.now())*1000000n;
const task={id:1n,revision:1n,projectId:[],title:'Replace meeting room switch',note:'',assignee:'agent',assigneeName:'Alex',assigneeAvailable:true,projectName:'Personal tasks',dueOn:'',column:{waiting:null},waitingFor:'Vendor delivery',createdBy:'agent',createdAt:now,updatedAt:now,archived:false};
const p={id:1n,revision:1n,name:'Office refresh',description:'Improve the network',scope:{group:'IT'},dueOn:'',createdBy:'agent',createdAt:now,updatedAt:now,archived:false,canManage:true,openTasks:1n,doneTasks:0n};
function fixture(extra={}){const dom=new JSDOM('<section id="root"></section>',{url:'https://desk.test/#/workboard'}),root=dom.window.document.querySelector('#root');let me={id:'agent',displayName:'Alex',role:'agent'};
 const backend={workboardHome:async()=>[{projects:[p],groups:['IT'],preferences:{projectId:[],mine:true,tickets:true,sales:true,completed:false}}],saveWorkboardPreferences:async()=>true,workboardProject:async()=>[{project:p,people:[{id:'agent',name:'Alex'}],history:[]}],workboardTask:async()=>[{task,people:[{id:'agent',name:'Alex'}],history:[],readOnly:false}],workboardTasks:async()=>[{rows:[task],total:1n,checkedAt:now}],workboardTickets:async()=>({rows:[{id:2n,title:'Desk request',reference:'SUP-2',column:{active:null},status:'open',next:'Continue checklist',owner:'Alex',updatedAt:now,dueOn:'',path:'#/t/2'}],total:1n,state:{ready:null},checkedAt:now}),workboardSources:async()=>[{cid:2n,name:'Assets',url:'https://assets.test'}],workboardSales:async()=>({state:{ready:null},rows:[{id:3n,title:'Laptop sale',reference:'INV-3',column:{active:null},next:'Record hand-over',owner:'Alex',updatedAt:now,dueOn:'',path:'#/sale/3'}],total:1n,checkedAt:now}),...extra};
 const view=createWorkboard({root,api:()=>backend,session:{load:()=> 'session'},getMe:()=>me});return {view,root,dom,backend,setMe:x=>{me=x;},close(){view.clear();dom.window.close();}};}
test('one compact board combines tasks and source records without workflow mutation',async()=>{const f=fixture();try{await f.view.show();assert.equal(f.root.querySelectorAll('.wb-column').length,4);assert.match(f.root.textContent,/Vendor delivery/);assert.match(f.root.textContent,/Record hand-over/);assert.equal(f.root.querySelector('[href="https://assets.test/#/sale/3"]').rel,'noopener noreferrer');assert.equal(f.root.querySelectorAll('[draggable]').length,0);assert.equal(f.root.querySelector('[data-source=sales]').checked,true);}finally{f.close();}});
test('revoked, offline and empty sources do not retain old sale cards',async()=>{const f=fixture();try{await f.view.show();assert.match(f.root.textContent,/Laptop sale/);f.backend.workboardSales=async()=>({state:{denied:null},rows:[],total:0n,checkedAt:now});await f.view.show();assert.doesNotMatch(f.root.textContent,/Laptop sale/);assert.match(f.root.textContent,/access restricted/);f.backend.workboardSources=async()=>{throw Error('offline');};await f.view.show();assert.match(f.root.textContent,/Sales could not be checked/);}finally{f.close();}});
test('late results cannot cross a sign-out or requester downgrade',async()=>{let release;const f=fixture({workboardHome:()=>new Promise(r=>{release=r;})});try{const load=f.view.show();f.setMe(null);f.view.clear();release([{projects:[],groups:[],preferences:{projectId:[]}}]);await load;assert.equal(f.root.textContent,'');f.setMe({id:'employee',role:'requester'});await f.view.show();assert.equal(f.root.textContent,'');}finally{f.close();}});
test('waiting requires a reason; failed saves retain the draft and block double submit',async()=>{let calls=0,release;const f=fixture({saveWorkTaskWithSubtasks:()=>{calls++;return new Promise(r=>{release=r;});}});try{await f.view.show('task','new');const form=f.root.querySelector('form');form.elements.title.value='Test the switch';form.elements.state.value='waiting';form.elements.state.onchange();assert.equal(form.elements.waiting.required,true);form.elements.waiting.value='Supplier';const send=form.onsubmit({preventDefault(){}});await form.onsubmit({preventDefault(){}});assert.equal(calls,1);release({err:{stale:null}});await send;assert.equal(form.elements.title.value,'Test the switch');assert.match(f.root.textContent,/changed. Reopen/);}finally{f.close();}});
test('untrusted titles render as text, and source links cannot change origin or carry credentials',async()=>{const f=fixture({workboardTasks:async()=>[{rows:[{...task,title:'<img src=x onerror=bad()>',waitingFor:'<script>bad()</script>'}],total:1n,checkedAt:now}]});try{await f.view.show();assert.equal(f.root.querySelector('img,script'),null);assert.match(f.root.textContent,/<img/);assert.equal(workLink('javascript:alert(1)','#/sale/1'),'');assert.equal(workLink('https://user:pass@assets.test','#/sale/1'),'');assert.equal(workLink('https://assets.test','//bad.test'),'');}finally{f.close();}});
test('project selection persists and archive restores remain discoverable',async()=>{const f=fixture({workboardTasks:async(_,filter,archived)=>[{rows:archived?[{...task,archived:true}]:[task],total:1n,checkedAt:now}]});try{await f.view.show('1');assert.equal(f.root.querySelector('#wb-project').value,'1');await f.view.show('projects');assert.match(f.root.textContent,/Archived tasks/);assert.ok(f.root.querySelector('[href="#/workboard/task/1"]'));}finally{f.close();}});
test('an unavailable personal owner has a truthful recovery path',async()=>{const f=fixture({workboardTask:async()=>[{task:{...task,assigneeAvailable:false},people:[],history:[],readOnly:false}]});try{await f.view.show('task','1');assert.match(f.root.textContent,/Archive this personal task or create a replacement/);assert.equal(f.root.querySelector('fieldset').disabled,true);assert.ok(f.root.querySelector('[data-archive-task]'));}finally{f.close();}});
test('subtasks save atomically with the task; incomplete children block Done without losing draft',async()=>{let payload,calls=0;const f=fixture({saveWorkTaskWithSubtasks:async(...args)=>{payload=args;calls++;return{err:{stale:null}};}});try{
 await f.view.show('task','1');const form=f.root.querySelector('form');f.root.querySelector('[data-add-subtask]').click();const child=f.root.querySelector('[data-subtask-row]');child.querySelector('[type=text]').value='<img src=x> check Wi-Fi';child.querySelector('[type=text]').dispatchEvent(new f.dom.window.Event('input',{bubbles:true}));form.elements.state.value='done';form.elements.state.onchange();await form.onsubmit({preventDefault(){}});assert.equal(calls,0);assert.match(f.root.textContent,/Complete every subtask/);child.querySelector('[type=checkbox]').checked=true;child.querySelector('[type=checkbox]').dispatchEvent(new f.dom.window.Event('input',{bubbles:true}));await form.onsubmit({preventDefault(){}});assert.equal(calls,1);assert.deepEqual(payload.at(-1),[{id:0n,title:'<img src=x> check Wi-Fi',done:true}]);assert.equal(child.querySelector('[type=text]').value,'<img src=x> check Wi-Fi');assert.equal(f.root.querySelector('img'),null);assert.match(f.root.textContent,/changed. Reopen/);
 }finally{f.close();}});
test('board shows subtask progress; archived tasks keep their checklist read-only',async()=>{const f=fixture({workboardTasks:async()=>[{rows:[{...task,subtaskCount:3n,subtasksDone:1n}],total:1n,checkedAt:now}],workboardTask:async()=>[{task:{...task,archived:true},subtasks:[{id:101n,title:'Check room',done:true}],people:[],history:[],readOnly:false}]});try{await f.view.show();assert.match(f.root.textContent,/1 of 3 subtasks complete/);await f.view.show('task','1');assert.equal(f.root.querySelector('[data-add-subtask]'),null);assert.equal(f.root.querySelector('[data-subtask-row] input').checked,true);assert.equal(f.root.querySelector('fieldset').disabled,true);}finally{f.close();}});

test('editing an unassigned team task does not silently take ownership',async()=>{const f=fixture({workboardTask:async()=>[{task:{...task,projectId:[p.id],assignee:'',assigneeName:''},subtasks:[],people:[{id:'agent',name:'Alex'}],history:[],readOnly:false}]});try{await f.view.show('task','1');assert.equal(f.root.querySelector('form').elements.owner.value,'');}finally{f.close();}});
