#!/usr/bin/env python3
"""Embed reviewed deployment sources in Motoko. No endpoint credentials in sources."""
from pathlib import Path
import json, plistlib, uuid, sys
root=Path(__file__).resolve().parents[1]
release=json.loads((root/'agent/release.json').read_text())
rev='0.7.2'
assets=release['assets']
lookup={'MAC':'osqueryd-macos-bare-5.23.0.tar.gz','LINUX_X64':'osquery-5.23.0_1.linux_x86_64.tar.gz','LINUX_ARM':'osquery-5.23.0_1.linux_aarch64.tar.gz','WIN_X64':'osquery-5.23.0.windows_x86_64.zip','WIN_ARM':'osquery-5.23.0.windows_arm64.zip'}
values={'VERSION':release['version'],'REVISION':rev}
for key,name in lookup.items():
    a=assets[name];assert a['url']==f'https://github.com/osquery/osquery/releases/download/{release["version"]}/{name}'
    assert len(a['sha256'])==64 and all(c in '0123456789abcdef' for c in a['sha256'])
    values[key+'_URL']=a['url'];values[key+'_SHA']=a['sha256']
def stamp(s):
    for k,v in values.items():s=s.replace('@@'+k+'@@',v)
    return s

def profile(name,title,content):
    ident='org.kebabstack.trust.'+name
    uid=lambda x:str(uuid.uuid5(uuid.NAMESPACE_DNS,x)).upper()
    payload={'PayloadIdentifier':ident+'.payload','PayloadUUID':uid(ident+'.payload'),'PayloadVersion':1,**content}
    return plistlib.dumps({'PayloadContent':[payload],'PayloadIdentifier':ident,'PayloadUUID':uid(ident),'PayloadVersion':1,'PayloadType':'Configuration','PayloadScope':'System','PayloadDisplayName':title,'PayloadDescription':('Manages only the named Trust background services.' if name=='background' else 'Suppresses ALL macOS background-item notifications, including other applications. Optional company policy, not a Trust-only setting.')},sort_keys=False).decode()
profiles={
 'background':profile('background','Trust · Background items',{'PayloadType':'com.apple.servicemanagement','Rules':[{'RuleType':'Label','RuleValue':v,'Comment':'Trust monitoring' if v.endswith('osqueryd') else 'Existing Trust updater during migration'} for v in ['org.kebabstack.trust.osqueryd','org.kebabstack.trust.update']]}),
 'notifications':profile('notifications','Trust · Quiet notifications (all background items)',{'PayloadType':'com.apple.notificationsettings','NotificationSettings':[{'BundleIdentifier':'com.apple.BTMNotificationAgent','NotificationsEnabled':False}]})}
outputs={root/'agent'/f'{k}.mobileconfig':v for k,v in profiles.items()}
# JSON string escaping matches Motoko here, excluding JSON's optional ASCII unicode escapes.
quote=lambda s:json.dumps(s,ensure_ascii=False)
code='// Generated by tools/build-agent-templates.py; edit agent sources, then regenerate.\nimport Text "mo:core/Text";\nmodule {\n  public type File = { name : Text; body : Text };\n  public let version = '+quote(release['version'])+';\n'
for k,file in [('unix','unix.sh'),('windows','windows.ps1')]:code+='  let '+k+' : Text = '+quote(stamp((root/'agent'/file).read_text()))+';\n'
for k,body in profiles.items():code+='  let '+k+' : Text = '+quote(body)+';\n'
code+='''  public func file(os : Text, kind : Text, host : Text, secret : Text, flags : Text, quiet : Bool) : ?File {
    if (os != "macos" and os != "linux" and os != "windows") return null;
    if (kind == "background" or kind == "notifications") {
      if (os != "macos") return null;
      return ?{ name = "trust-" # kind # ".mobileconfig"; body = if (kind == "background") background else notifications };
    };
    if (kind != "install" and kind != "migrate" and kind != "preflight" and kind != "audit" and kind != "uninstall" and kind != "audit-removed") return null;
    let action = if (kind == "migrate") "install" else kind;
    let containsSecret = kind == "install" or kind == "migrate";
    if (containsSecret and secret == "") return null;
    var body = if (os == "windows") windows else unix;
    for ((key, value) in [("ACTION", action), ("HOST", host), ("SECRET", if (containsSecret) secret else ""), ("FLAGS", flags), ("OS", os), ("QUIET", if (quiet) "true" else "false"), ("MIGRATE", if (kind == "migrate") "1" else "0")].vals()) {
      body := Text.replace(body, #text ("@@" # key # "@@"), value);
    };
    ?{ name = "trust-" # os # "-" # kind # (if (os == "windows") ".ps1" else ".sh"); body };
  };
};
'''
outputs[root/'backend/lib/AgentDeployment.mo']=code
for p,body in outputs.items():
    if '--check' in sys.argv:
        if not p.exists() or p.read_text()!=body:sys.exit(f'Generated deployment file drift: {p}')
    else:p.write_text(body)
print('Deployment sources in step' if '--check' in sys.argv else 'Deployment sources generated')
