#!/usr/bin/env node
/** Deterministic, offline design-doc build. No runtime app token mutation. */
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import {catalogue} from './site/catalogue.mjs';
const root=fileURLToPath(new URL('../',import.meta.url));
const read=async file => readFile(path.join(root,file),'utf8');
const standard=JSON.parse(await read('design/standard.json'));
const tokens=JSON.parse(await read('design/tokens.json'));
const adoption=JSON.parse(await read('design/adoption.json'));
const brand=JSON.parse(await read('design/brand/registry.json'));
const product=JSON.parse(await read('design/logos/registry.json'));
const check=process.argv.includes('--check'), drift=[];
const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function output(file,body){const dest=path.join(root,file);let actual;try{actual=await readFile(dest,'utf8');}catch{}if(actual===body)return;if(check){drift.push(file);return;}await mkdir(path.dirname(dest),{recursive:true});await writeFile(dest,body);}
const kit=catalogue({tokens,brand,product,esc});
const ids=new Set();
for(const section of standard.sections){if(ids.has(section.id))throw Error('Duplicate chapter '+section.id);ids.add(section.id);for(const rule of section.rules){if(ids.has(rule.id)||!['must','should'].includes(rule.level)||!rule.body||!rule.verify)throw Error('Invalid rule '+rule.id);ids.add(rule.id);}}
if(standard.version!==tokens.version||standard.version!==adoption.version)throw Error('Design source versions disagree');
const ruleCount=standard.sections.reduce((n,s)=>n+s.rules.length,0);
const ruleHtml=r=>`<article class="rule" id="${r.id}" tabindex="-1" data-search="${esc([r.id,r.title,r.body,r.verify,r.example || '',...(r.keywords || [])].join(' '))}"><div class="rule-top"><a class="rule-id" href="#${r.id}" aria-label="Link to rule ${r.id}">${r.id}</a><span class="level ${r.level}">${r.level}</span></div><h2>${esc(r.title)}</h2><p>${esc(r.body)}</p>${r.example?`<blockquote>${esc(r.example)}</blockquote>`:''}<div class="verify"><strong>Verify</strong><span>${esc(r.verify)}</span></div></article>`;
let group='';
const nav=standard.sections.map(s=>{const heading=s.group!==group?`<p class="nav-group">${esc(s.group)}</p>`:'';group=s.group;return heading+`<a href="#${s.id}">${esc(s.title)}</a>`;}).join('\n');
const chapterLinks=standard.sections.map((s,i)=>`<a class="chapter-link" href="#${s.id}"><span class="mono muted">${String(i+1).padStart(2,'0')}</span><span><b>${esc(s.title)}</b><small>${s.rules.length} rules · ${esc(s.group)}</small></span><span aria-hidden="true">↗</span></a>`).join('');
const chapters=standard.sections.map((s,i)=>`<section class="page" id="${s.id}" aria-labelledby="heading-${s.id}"><header class="page-head"><p class="eyebrow">${esc(s.group)} · ${String(i+1).padStart(2,'0')} / ${standard.sections.length}</p><h1 id="heading-${s.id}" tabindex="-1">${esc(s.title)}</h1><p class="intro">${esc(s.intro)}</p></header>${s.id==='identity'?'<p><a class="button" href="#brand">Kebabstack logo & usage →</a> <a class="button" href="logos/">Product logo library ↗</a></p>':''}${s.id==='components'?kit.links:''}${s.id==='visual'?'<p><a class="button" href="#reference">Explore tokens & components →</a></p>':''}${s.id==='accessibility'?'<p class="small">Reference: <a href="https://www.w3.org/WAI/WCAG22/quickref/">W3C · WCAG 2.2</a>. Full conformance requires an audit of the actual implementation.</p>':''}${s.rules.map(ruleHtml).join('\n')}<div class="page-foot"><a href="${i?'#'+standard.sections[i-1].id:'#overview'}">← ${esc(i?standard.sections[i-1].title:'Start here')}</a><a href="${i<standard.sections.length-1?'#'+standard.sections[i+1].id:'#adoption'}">${esc(i<standard.sections.length-1?standard.sections[i+1].title:'Adoption & review')} →</a></div></section>`).join('\n');
const tokenLabels={bg:'Warm paper',surface:'Work surface',ink:'Primary text',secondary:'Secondary text',accent:'Forest action','accent-soft':'Quiet emphasis',logo:'Product mark',focus:'Keyboard focus'};
const swatches=Object.entries(tokenLabels).map(([key,label])=>`<div class="swatch"><div class="swatch-color" style="--swatch:var(--ds-${key})"></div><div class="swatch-label"><strong>${label}</strong><code>${esc(key)} · ${tokens.light[key]}</code><code class="dark-value"> / ${tokens.dark[key]}</code></div></div>`).join('');
const tokenRows=[['Spacing','4 / 8 / 12 / 16 / 24 / 32 / 48 / 64 px','Group related work tightly; separate different decisions.'],['Radius','8 px control · 16 px panel','Pills are for short statuses, not every action.'],['Width','720 px reading · 1280 px work · 1600 px operations','Wider pages need a real comparison task.'],['Controls','44 px default · 36 px dense desktop','Keep adequate spacing and accessible target size.'],['Motion','120 / 180 / 240 ms','Feedback / state / panel. Reduced motion removes animation.'],['Layers','0 / 10 / 20 / 30 / 40 / 50','Base / sticky / menu / scrim / dialog / toast.']].map(r=>`<tr>${r.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('');
const waveHtml=adoption.waves.map(w=>`<article class="wave"><div class="wave-head"><h2>${esc(w.title)}</h2><span class="badge ${w.status==='Gap found'?'warning':''}">${esc(w.status)}</span></div><p class="scope">${esc(w.scope)}</p><p><strong>${esc(w.job)}</strong></p><p>${esc(w.checks)}</p>${w.evidence?`<p class="small">${esc(w.evidence)}</p>`:''}</article>`).join('');
const gates=adoption.checklist.map((g,i)=>`<li><strong>${String(i+1).padStart(2,'0')} · ${esc(g[0])}</strong><p>${esc(g[1])}</p></li>`).join('');
const html=`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light dark"><meta name="description" content="The Kebabstack Brand & Product System: one shared foundation for clear, useful and trustworthy IT tools."><title>Kebabstack · Brand & Product System</title><link rel="icon" href="favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="reference-tokens.css"><link rel="stylesheet" href="standard.css"></head>
<body><a class="skip" href="#main">Skip to content</a><header class="masthead"><a class="wordmark" href="#overview" aria-label="Kebabstack · Brand & product system"><span>${kit.lockup()}<small>Brand & product system</small></span></a><div class="masthead-actions"><span class="version">v${standard.version}</span><label class="theme-control"><span>Appearance</span><select id="theme" aria-label="Appearance"><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select></label><button id="nav-toggle" aria-expanded="false" aria-controls="sidebar">Browse</button></div></header>
<div class="frame"><aside class="sidebar" id="sidebar"><label class="search-label" for="rule-search">Find a rule or component</label><div class="searchbox"><input id="rule-search" type="search" placeholder="Try logo, tabs or SSO" autocomplete="off"><button id="clear-search" aria-label="Clear search" hidden>×</button></div><nav aria-label="Design standard"><a href="#overview">Start here</a><p class="nav-group">Visual catalogue</p><a href="#reference">Colours & foundations</a><a href="#brand">Kebabstack logo</a><a href="#buttons">Buttons</a><a href="#menus">Menus & tabs</a><a href="#fields">Fields & panels</a><a href="#workspace">Workspace composition</a>${nav}<div class="nav-divider"><a href="#adoption">Adoption & review</a><a href="logos/">Logo library ↗</a><a href="STANDARD.md">All rules · Markdown ↗</a></div></nav></aside>
<main id="main" tabindex="-1"><noscript><p class="nojs-note">All chapters are available below. Search, theme selection and examples become interactive with JavaScript enabled.</p></noscript>
<section class="page is-active" id="overview" aria-labelledby="heading-overview"><header class="hero"><p class="eyebrow">The way we build Kebabstack</p><h1 id="heading-overview" tabindex="-1">Less work.<br><span>More confidence.</span></h1><p>Help IT finish the job, understand what happens next and build the next useful automation. Every tool. Every screen. One clear system.</p><div class="actions"><a class="button primary" href="#purpose">Read the principles →</a><a class="button" href="#reference">Explore the design language</a></div><div class="status-line"><span class="status-dot" aria-hidden="true"></span><span>Standard ${standard.version}</span><span aria-hidden="true">·</span><span>${standard.sections.length} chapters · ${ruleCount} rules</span><span aria-hidden="true">·</span><span>App adoption is reviewed separately</span></div></header>
<div class="principles"><article><span class="principle-number">01 / Remove work</span><h2>Less to configure.<br>More to get done.</h2><p>Reuse what we know. Pick sensible defaults. Automate repeated chores with a clear owner and a safe recovery path.</p></article><article><span class="principle-number">02 / Explain the next step</span><h2>Show the action.<br>Name the responsibility.</h2><p>Current state, next actor, real blocker. Keep supporting detail close without making it compete with the work.</p></article><article><span class="principle-number">03 / Earn trust</span><h2>Evidence before<br>reassurance.</h2><p>Saved is not always confirmed. Missing data is not a healthy result. Make uncertainty visible and useful.</p></article></div>
<div class="section-heading"><h2>What that feels like</h2><span class="small muted">Interactive design example</span></div>
<div class="specimen"><div class="specimen-label"><span>Assets / Sale · fictitious example</span><span>No live data or actions</span></div><div class="specimen-content"><div class="demo-head"><div><span class="small muted">SALE-0042</span><h3>MacBook Pro · 14-inch</h3><p>A clear outcome, without the noise.</p></div><span id="demo-status" class="badge success">Ready for handover</span></div><ol class="steps" id="demo-steps" aria-label="Sale progress"><li>01 · Offer</li><li>02 · Invoice</li><li aria-current="step">03 · Paid</li><li>04 · Complete</li></ol><div class="next-action"><div><p class="eyebrow" id="demo-actor">IT · Next step</p><h3 id="demo-title">Record the physical handover</h3><p id="demo-description">Payment and preparation are confirmed. Record the handover only after the device is given to the buyer.</p></div><button class="primary" id="demo-action">Preview handover</button></div><div class="demo-controls"><label for="demo-state">Explore a different state<select id="demo-state"><option value="ready">Ready to act</option><option value="blocked">Waiting on someone else</option><option value="pending">Result not confirmed</option><option value="unavailable">Source unavailable</option><option value="complete">Complete</option></select></label><p>Same visual language. Different evidence, responsibility and next action.</p></div><p class="small secondary" id="demo-message" role="status"></p></div></div>
<div class="notice"><strong>A target, with an honest migration path.</strong><p>This standard sets the rules for new and revised work. Existing apps are reviewed in step two. Their current appearance or behavior is not automatically certified by this page.</p><a href="#adoption">See the review order and acceptance gates →</a></div>
<div class="section-heading"><h2>The complete system</h2><span class="small muted">Design + behavior</span></div><div class="chapter-grid">${chapterLinks}</div></section>
<section class="page" id="reference" aria-labelledby="heading-reference"><header class="page-head"><p class="eyebrow">Reference · target tokens</p><h1 id="heading-reference" tabindex="-1">Quiet visuals.<br>Clear decisions.</h1><p class="intro">Warm paper, forest actions and restrained linework. The visual foundation supports the task instead of competing with it.</p>${kit.links}</header><div class="notice">These are reference tokens for the next shared migration. The current runtime source remains <code>hub/dist/tokens.css</code>. The logo registry stays at version 1.0.0 with its approved geometry.</div><div class="section-heading"><h2>Semantic colour</h2><a href="tokens.json" class="small">Download tokens.json ↗</a></div><div class="swatches">${swatches}</div><p class="palette-note">Each swatch lists light / dark values. Change Appearance to inspect the active palette. Sage identifies product marks; it is not a general-purpose small-text colour.</p>
<div class="section-heading"><h2>Type & hierarchy</h2><span class="small muted">UI sans · technical mono</span></div><div class="spec-grid"><div><div class="type-spec"><small>PAGE TITLE · 32–40 / 1.15 · 550</small><p style="font-size:36px;letter-spacing:-.04em">Everything in its place.</p></div><div class="type-spec"><small>SECTION · 24 / 1.2 · 550</small><p style="font-size:24px">Your next useful action</p></div><div class="type-spec"><small>BODY · 16 / 1.6 · 400</small><p style="font-size:16px;line-height:1.6">Show what changed, who acts next and how to verify the result.</p></div><div class="type-spec"><small>TECHNICAL METADATA · 12 / 1.5</small><code>POLICY-042 · revision 3</code></div></div><div><h3>Every colour has a job</h3><div class="actions"><span class="badge success">Confirmed</span><span class="badge warning">Needs attention</span><span class="badge danger">Failed</span><span class="badge info">Awaiting confirmation</span><span class="badge">Not checked</span></div><p class="palette-note">Always pair colour with words. Never use an empty or neutral state to imply success.</p><div class="field-demo"><label for="example-email">Support email · validation example</label><input id="example-email" type="text" value="support@" aria-invalid="true" aria-describedby="example-email-error" readonly><small id="example-email-error">Enter a complete email address, such as support@example.com.</small></div><p class="palette-note">Reference only: the value is read-only. Labels stay visible, the draft survives and the error explains the correction.</p></div></div>
<div class="section-heading"><h2>Rhythm & dimensions</h2></div><div class="table-scroll" tabindex="0" role="region" aria-label="Design dimensions"><table class="token-table"><thead><tr><th scope="col">Foundation</th><th scope="col">Reference</th><th scope="col">Purpose</th></tr></thead><tbody>${tokenRows}</tbody></table></div><div class="notice"><strong>Accessible by construction, verified in context.</strong><p>The checked token pairs meet their recorded contrast thresholds. Actual components still require keyboard, screen-reader, zoom and rendered-state review. <a href="#accessibility">Read the accessibility rules →</a></p></div><div class="actions"><a class="button" href="logos/">Browse product marks ↗</a><a class="button" href="reference-tokens.css">Reference CSS ↗</a><a class="button" href="UI-REFERENCE.md">Component dimensions ↗</a><a class="button" href="#components">Component behavior →</a></div></section>
${kit.html}
${chapters}
<section class="page" id="adoption" aria-labelledby="heading-adoption"><header class="page-head"><p class="eyebrow">Step two · deliberate adoption</p><h1 id="heading-adoption" tabindex="-1">One foundation.<br>Then every solution.</h1><p class="intro">Review real jobs and every relevant role. Fix confusing logic before polishing the surface. Verify each change without losing the workflows people already rely on.</p></header><div class="notice"><strong>Current status:</strong> ${esc(adoption.status)} <a href="reviews/2026-09-22-suite-standard.md">Read the suite adoption record →</a> Full workflow certification needs its own evidence.</div>${waveHtml}<div class="section-heading"><h2>The acceptance gates</h2><a class="small" href="REVIEW-TEMPLATE.md" download>Download review template ↗</a></div><ol class="checklist">${gates}</ol><div class="notice"><strong>A score cannot hide a critical defect.</strong><p>Access/data integrity defects and blocked core or accessible tasks stop the affected release. Record gaps with a rule ID, reproduction, impact, owner and evidence. Unreviewed does not mean passed.</p></div><div class="actions"><a class="button primary" href="REVIEW-TEMPLATE.md" download>Get the review template</a><a class="button" href="ADOPTION.md">Read the adoption plan ↗</a></div></section>
<section class="page" id="search-results" aria-labelledby="heading-search"><header class="page-head"><p class="eyebrow">Across the standard</p><h1 id="heading-search" tabindex="-1">Find the right reference.</h1><p id="results-count" role="status" class="intro"></p></header><p id="no-results" hidden>No matching references. Try a shorter term such as access, privacy, SSO or workflow.</p><div id="results-list"></div></section>
<footer class="site-footer"><span>Kebabstack · Brand & Product System ${standard.version}<br>${esc(standard.date)} · Normative target, separately verified adoption</span><span><a href="README.md">Source guide</a> · <a href="CHANGELOG.md">Changelog</a> · <a href="STANDARD.md">All rules</a><br>No trackers. No external fonts. Fictitious examples.</span></footer></main></div>
<dialog id="demo-dialog" aria-labelledby="demo-dialog-title" aria-describedby="demo-dialog-description"><p class="eyebrow">Confirmation example</p><h2 id="demo-dialog-title">Record this handover?</h2><p id="demo-dialog-description">This demonstration covers one device and one sale. A real confirmation must be based on the physical handover and current preparation evidence.</p><div class="notice">This is a local design example. It does not update a device, contact a buyer or change any sale.</div><div class="actions"><button id="demo-cancel" autofocus>Cancel</button><button id="demo-confirm" class="primary">Complete example</button></div></dialog><script src="standard.js" defer></script></body></html>\n`;
let css='/* Generated from design/tokens.json. Reference only; not the runtime SDK stylesheet. */\n';
const vars=palette=>Object.entries(palette).map(([key,value])=>`--ds-${key}:${value};`).join('');
css+=`:root{color-scheme:light;${vars(tokens.light)}--ds-font-ui:${tokens.fonts.ui};--ds-font-mono:${tokens.fonts.mono};${kit.css}}\n`;
css+=`@media(prefers-color-scheme:dark){:root:not([data-theme=light]){color-scheme:dark;${vars(tokens.dark)}}}\n[data-theme=dark]{color-scheme:dark;${vars(tokens.dark)}}\n`;
css+=`@media print{:root,:root[data-theme]{color-scheme:light;${vars(tokens.light)}}}\n`;
let markdown=`# ${standard.title}\n\nVersion **${standard.version}** · ${standard.date}\n\n${standard.status}.\n\n${standard.tagline}\n\nGenerated from [standard.json](standard.json). Edit the source, not this file.\n\n**Must** is required. **Should** is the default, with a documented reason for deviation.\nExceptions and acceptance gates are defined under Governance.\n\n`;
for(const s of standard.sections){markdown+=`## ${s.title}\n\n${s.intro}\n\n`;for(const r of s.rules)markdown+=`### ${r.id} · ${r.title} (${r.level})\n\n${r.body}\n\n${r.example?'> '+r.example+'\n\n':''}**Verify:** ${r.verify}\n\n`;}
markdown+='## Primary references\n\n- [WCAG 2.2 quick reference](https://www.w3.org/WAI/WCAG22/quickref/) — accessibility acceptance target, not a conformance certification.\n- [Text resize](https://www.w3.org/WAI/WCAG22/Understanding/resize-text.html), [target size](https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum.html), [accessible authentication](https://www.w3.org/WAI/WCAG22/Understanding/accessible-authentication-minimum.html) — implementation context.\n- [Suite identity](brand/README.md), [product logo rules](logos/README.md), [tokens](tokens.json), [component dimensions](UI-REFERENCE.md) and [adoption plan](ADOPTION.md).\n- Exact runtime permission behavior: repository `docs/APP-PERMISSIONS.md`; this product standard does not replace its enforcement contract.\n';
let adoptionMd=`# Adopting the Kebabstack product standard\n\nVersion ${standard.version}. ${adoption.status}\n\nStep one defines the shared standard. Step two reviews and migrates actual apps.\nThe order below is a plan, not a claim that the work has already been done.\n\n`;
for(const w of adoption.waves)adoptionMd+=`## ${w.title}\n\n**Scope:** ${w.scope}. **Status:** ${w.status}.\n\n${w.job}\n\n${w.checks}\n\n${w.evidence?w.evidence+'\n\n':''}`;
adoptionMd+='## Runtime migration contract\n\n`tokens.json` is the target reference. `hub/dist/tokens.css` stays the current\nruntime authority until the shared migration is reviewed. Map existing `--ks-bg`,\n`--ks-bg-card`, `--ks-fg`, `--ks-fg-secondary`, `--ks-accent`, `--ks-focus` and\nrelated runtime roles to the reference semantics; remove redundant per-app\noverrides only after comparison. `reference-tokens.css` is scoped to the design\ndocumentation and is not a second application SDK.\n\nInventory each app override, check both themes and representative layouts, then\nchange the canonical runtime source and synchronize its copies. Use the existing\nshared sign-in and client; do not rebuild permission logic in a design component.\nRun role/state/frontend checks and the release checks required by the change.\nPreserve directory/Lunch behavior, stable contracts and production deployment\nplaceholders. Ship through the existing reviewed release process.\n\n## Acceptance checklist\n\n';
for(const g of adoption.checklist)adoptionMd+=`- **${g[0]}:** ${g[1]}\n`;
adoptionMd+='\n## Priorities\n\n';for(const [priority,meaning] of Object.entries(adoption.severities))adoptionMd+=`- **${priority}:** ${meaning}\n`;
adoptionMd+='\n## Record evidence\n\nUse [REVIEW-TEMPLATE.md](REVIEW-TEMPLATE.md). Record date, commit, module version,\nrole, data scope, viewport, theme and evidence per task. Do not substitute a\nvisual screenshot for authorization or data-integrity verification. Keep\nproduction/customer evidence outside the public repository.\n\nAn exception records the rule, owner, reason, scope, compensating measure and\nreview date. A skipped or untested path is never passed. A verified surface can\nstill have explicitly recorded noncritical gaps; do not imply certification.\n';
const suiteSvg=color=>`<svg xmlns="http://www.w3.org/2000/svg" viewBox="${brand.viewBox}" style="color:${color}">${brand.geometry}</svg>\n`;
const lockupHtml=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Kebabstack logo lockup</title><style>:root{${kit.css}}body{margin:32px;font-family:var(--suite-font);background:var(--suite-paper);color:var(--suite-ink)}.suite-lockup{display:inline-flex;align-items:center;gap:var(--suite-gap);font-family:var(--suite-font);font-size:var(--suite-text);font-weight:var(--suite-weight);letter-spacing:var(--suite-tracking);line-height:1.5;white-space:nowrap}.suite-mark{width:var(--suite-mark-width);height:var(--suite-mark-height);flex:none}.suite-hyphen{color:var(--suite-hyphen)}@media(prefers-color-scheme:dark){body{background:var(--suite-dark);color:var(--suite-light)}.suite-hyphen{color:var(--suite-hyphen-dark)}}</style></head><body><div aria-label="Kebabstack">${kit.lockup()}</div></body></html>\n`;
const generated={'UI-REFERENCE.md':kit.markdown,'brand/mark-light.svg':suiteSvg(brand.colors.ink),'brand/mark-dark.svg':suiteSvg(brand.colors.lightRod),'brand/favicon.svg':await read(brand.faviconSource),'brand/lockup.html':lockupHtml,'favicon.svg':await read('website/public/favicon.svg'),'index.html':html,'reference-tokens.css':css,'standard.css':await read('design/site/standard.css')+'\n'+await read('design/site/catalogue.css'),'standard.js':await read('design/site/standard.js'),'STANDARD.md':markdown,'ADOPTION.md':adoptionMd};
for(const [name,content] of Object.entries(generated)){await output('design/'+name,content);await output('hub/dist/design/'+name,content);}
for(const file of ['README.md','CHANGELOG.md','REVIEW-TEMPLATE.md','standard.json','tokens.json','adoption.json','brand/registry.json','brand/README.md','reviews/2026-09-22-suite-standard.md'])await output('hub/dist/design/'+file,await read('design/'+file));
if(drift.length){console.error('Design drift: run npm run design:build\n'+drift.join('\n'));process.exit(1);}
console.log(`Design ${standard.version}: ${standard.sections.length} chapters, ${ruleCount} rules ${check?'verified':'generated'}.`);
