import {test} from 'node:test';
import assert from 'node:assert/strict';
import {receiveEmail} from '../src/receive.js';
const env={ALLOWED_RECIPIENTS:'contracts@relay.example',MAILBOX_ADDRESS:'contracts@example'};
function fixture(overrides={}){const events=[];return {events,message:{to:'contracts@relay.example',from:'sender@example',rawSize:20,raw:'mail',headers:new Headers(),setReject:r=>events.push(['reject',r]),forward:async(to,h)=>events.push(['forward',to,h.get('X-Kebab-Relay-Failed')])},deps:{read:async()=>new Uint8Array(20),parse:async()=>({}),prepare:async()=>({meta:{},parts:[]}),deliver:async()=>({ok:true,sourceId:1}),log:()=>{},...overrides}};}
for(const stage of ['read','parse','prepare','deliver'])test(`delivery failure during ${stage} preserves recovery path`,async()=>{const f=fixture({[stage]:async()=>{throw Error('fixture');}});await receiveEmail(f.message,{...env,FALLBACK_ADDRESS:'recovery@example'},f.deps);assert.deepEqual(f.events[0].slice(0,2),['forward','recovery@example']);});
test('logical canister refusal without fallback is rejected instead of acknowledged',async()=>{const f=fixture({deliver:async()=>({ok:false,detail:'no relay access'})});await receiveEmail(f.message,env,f.deps);assert.equal(f.events[0][0],'reject');});
test('incomplete attachment set goes to recovery without partial commit',async()=>{let delivered=false;const f=fixture({prepare:async()=>({incomplete:true}),deliver:async()=>{delivered=true;}});await receiveEmail(f.message,{...env,FALLBACK_ADDRESS:'recovery@example'},f.deps);assert.equal(delivered,false);assert.equal(f.events[0][0],'forward');});
test('failed recovery rejects; configured public mailbox cannot create a forwarding loop',async()=>{for(const fallback of ['recovery@example','contracts@example']){const f=fixture({deliver:async()=>({ok:false})});f.message.forward=async()=>{throw Error('destination unavailable')};await receiveEmail(f.message,{...env,FALLBACK_ADDRESS:fallback},f.deps);assert.equal(f.events[0][0],'reject');}});
test('committed sources and known duplicates are accepted without forwarding',async()=>{for(const result of [{ok:true,sourceId:1},{ok:false,duplicate:true,sourceId:1}]){const f=fixture({deliver:async()=>result});await receiveEmail(f.message,env,f.deps);assert.deepEqual(f.events,[]);}});
test('missing recipient allowlist fails closed before reading mail',async()=>{const f=fixture({read:async()=>{throw Error('must not read')}});await receiveEmail(f.message,{},f.deps);assert.equal(f.events[0][0],'reject');});
