import {JSDOM} from 'jsdom';import {readFileSync} from 'node:fs';import {test} from 'node:test';import assert from 'node:assert/strict';
const source=readFileSync(new URL('../js/hub-client.js',import.meta.url),'utf8').replace(/^export (const|function) /gm,'$1 ');
const delay=()=>new Promise(r=>setTimeout(r,10));
function fixture(){const dom=new JSDOM('<div id="topbar"></div><input id="note">',{url:'https://app.test/',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;w.matchMedia=()=>({matches:false});w.eval(source);const bar=w.mountTopbar(w.document.querySelector('#topbar'),{app:{id:'assets',name:'Assets'},person:{displayName:'Test User'}});return {dom,w,bar,find:id=>w.document.getElementById(id)};}
test('outside pointer dismissal keeps focus on the chosen workspace control; Escape restores the opener',async()=>{const f=fixture();try{f.find('ks-menuBtn').click();await delay();assert.equal(f.w.document.activeElement.id,'ks-find');f.find('note').focus();f.find('note').click();assert.equal(f.find('ks-appsPanel').hidden,true);assert.equal(f.w.document.activeElement.id,'note');f.find('ks-menuBtn').click();await delay();f.w.document.dispatchEvent(new f.w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert.equal(f.w.document.activeElement.id,'ks-menuBtn');assert.equal(f.find('ks-menuBtn').getAttribute('aria-expanded'),'false');}finally{f.bar.destroy();f.dom.window.close();}});
test('closing or destroying a newly opened panel cannot steal focus later',async()=>{for(const destroy of [false,true]){const f=fixture();try{f.find('ks-menuBtn').click();if(destroy)f.bar.destroy();else f.bar.closeAll();f.find('note').focus();await delay();assert.equal(f.w.document.activeElement.id,'note');}finally{f.bar.destroy();f.dom.window.close();}}});

test('mount host owns the sticky header and releases layout on destroy',()=>{const f=fixture();try{const host=f.find('topbar'),header=host.querySelector('[role=banner]');assert.equal(f.w.getComputedStyle(host).position,'sticky','the header-sized wrapper must stick, not only its child');assert.equal(f.w.getComputedStyle(host).top,'0px');assert.equal(f.w.getComputedStyle(host).flexShrink,'0','a short viewport must not compress the global bar');assert.equal(f.w.getComputedStyle(header).position,'static');f.bar.destroy();assert.equal(host.classList.contains('ks-topbar-host'),false);assert.equal(host.childElementCount,0);}finally{f.bar.destroy();f.dom.window.close();}});

function roleFixture(){const dom=new JSDOM('<div id="topbar"></div>',{url:'https://app.test/',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;w.eval(source);let value=[{email:'owner@example.test',hubRole:['owner'],active:true,expiresAt:BigInt(Date.now()+60000)*1000000n,unread:0n}];const actor={suiteState:async()=>value,myAvatarPortal:async()=>[],getCompanyLogo:async()=>[]};const bar=w.mountTopbar(w.document.querySelector('#topbar'),{hubUrl:'https://hub.test/',hub:{actor,token:'suite'},app:{id:'assets',name:'Assets'},person:{role:'admin'}});return{dom,w,bar,actor,set:v=>{value=v},link:()=>w.document.getElementById('ks-consoleLink')};}
test('Hub link follows the live global role, never an app-local role or old Hub',async()=>{const f=roleFixture();try{await f.bar.refresh();assert.equal(f.link().hidden,false);assert.equal(f.link().href,'https://hub.test/?console=1#/home');for(const role of ['owner','admin','helpdesk','member','',undefined]){f.set([{active:true,hubRole:role?[role]:[],expiresAt:BigInt(Date.now()+60000)*1000000n}]);await f.bar.refresh();assert.equal(f.link().hidden,!['owner','admin','helpdesk'].includes(role));}f.set([]);await f.bar.refresh();assert.equal(f.link().hidden,true);}finally{f.bar.destroy();f.dom.window.close()}});
test('revocation, expiry, query failure and token changes hide the console link; stale requests cannot restore it',async()=>{const f=roleFixture();try{await f.bar.refresh();for(const change of [{active:false,expiresAt:BigInt(Date.now()+60000)*1000000n},{active:true,expiresAt:1n}]){f.set([{hubRole:['owner'],...change}]);await f.bar.refresh();assert.equal(f.link().hidden,true);}f.actor.suiteState=async()=>{throw Error('unavailable')};await f.bar.refresh();assert.equal(f.link().hidden,true);let oldFinish;f.actor.suiteState=()=>new Promise(r=>oldFinish=r);const old=f.bar.refresh();f.actor.suiteState=async()=>[];f.bar.setToken('new-session');assert.equal(f.link().hidden,true);await delay();oldFinish([{hubRole:['owner'],active:true,expiresAt:BigInt(Date.now()+60000)*1000000n}]);await old;assert.equal(f.link().hidden,true);}finally{f.bar.destroy();f.dom.window.close()}});
